import { useRef, useEffect, useState, Suspense } from 'react'
import { Link } from 'react-router-dom'
import Lenis from 'lenis'
import { m, AnimatePresence, useScroll, useTransform, MotionConfig } from 'framer-motion'
import useLowPowerMode from '../hooks/useLowPowerMode'
import { useAuth } from '../providers/AuthContext'
import { Helmet } from 'react-helmet-async'
import React from 'react'
import CursorGlow from '../components/CursorGlow'
import MagneticButton from '../components/MagneticButton'
import CountUp from '../components/CountUp'
import { DOSHA_COLOR } from '../constants/dosha'
import {
  ShieldCheck, Sparkles, Leaf, Zap, Dna, Dumbbell,
  Salad, Pill, Flower2, Soup, HeartPulse, TriangleAlert, Check,
} from 'lucide-react'
import './Landing.css'

// ─── Animation variants ───────────────────────────────────────
const wordVariants = {
  hidden: { opacity: 0, y: 32, filter: 'blur(4px)' },
  visible: { opacity: 1, y: 0, filter: 'blur(0px)' },
}
const stagger = { visible: { transition: { staggerChildren: 0.09 } } }
const fadeUp   = { hidden: { opacity: 0, y: 36 }, visible: { opacity: 1, y: 0 } }
const fadeLeft = { hidden: { opacity: 0, x: -48 }, visible: { opacity: 1, x: 0 } }
const fadeRight= { hidden: { opacity: 0, x:  48 }, visible: { opacity: 1, x: 0 } }
const VP       = { once: true, margin: '-60px' }

// ─── Hero title words ──────────────────────────────────────────
const HERO_WORDS = ['Your', 'wellness,', 'finally', 'in', 'sync.']

// True when this module loads over PRERENDERED HTML (cold visit to "/"): the
// hero already exists in the DOM before React hydrates. In that case skip the
// hero entrance animations — re-animating content the visitor is already
// reading looks like a glitch, and the re-paint pushes the LCP timestamp from
// first paint (~1.6s) to post-hydration (~3s) on slow devices. Client-side
// navigations to "/" (no prerendered DOM at module load) keep the entrance.
const PRERENDERED = typeof document !== 'undefined' && !!document.querySelector('.lnd-hero-subtitle')

// ─── How it works cards ───────────────────────────────────────
const HOW_CARDS = [
  {
    id: 'profile', step: 'Step 01',
    Icon: Dna,
    title: 'Build Your Dosha Profile',
    desc: 'Answer a deep constitution quiz and our AI maps your Vata, Pitta, Kapha balance into a living health fingerprint.',
  },
  {
    id: 'plans', step: 'Step 02',
    Icon: Sparkles,
    title: 'AI Crafts Your Protocol',
    desc: 'Personalised gym, yoga, nutrition, detox, and remedy plans — generated in seconds and recalibrated daily.',
  },
  {
    id: 'sync', step: 'Step 03',
    Icon: HeartPulse,
    title: 'Adaptive Intelligence, Daily',
    desc: "Check in on energy, mood, and sleep. Plans evolve automatically so you're always in the right zone.",
  },
]

// ─── Feature sections ─────────────────────────────────────────
const FEATURES = [
  {
    tag: 'Dosha Intelligence',
    title: 'Wellness plans that understand your body',
    desc: 'Not generic routines — deeply personalised protocols built from Ayurvedic principles and your unique constitution. Your Vata-Pitta-Kapha balance drives every recommendation.',
    list: ['Prakriti constitution mapping', 'Vikriti imbalance detection', 'Daily adaptive re-scoring'],
    Icon: Dna,
    reversed: false,
    Visual: DoshaFeatureVisual,
  },
  {
    tag: 'AI-Powered Plans',
    title: 'Six pillars of health, unified',
    desc: 'Gym splits, yoga flows, Ayurvedic meals, panchakarma detox, home remedies, and herbal formulations — all generated by AI, all tailored to you.',
    list: ['Gym & yoga sequence generation', 'Dosha-matched meal timing', 'Seasonal detox protocols'],
    Icon: Dumbbell,
    reversed: true,
    Visual: PlansFeatureVisual,
  },
  {
    tag: 'Safety First',
    title: 'Guided by Ayurveda, verified by science',
    desc: 'Every remedy and herbal recommendation passes through a safety layer that screens for contraindications with your medications, allergies, and conditions.',
    list: ['Drug-herb interaction screening', 'Condition-aware filtering', 'Medical disclaimer guardrails'],
    Icon: ShieldCheck,
    reversed: false,
    Visual: SafetyFeatureVisual,
  },
]

// ─── Testimonials ─────────────────────────────────────────────
const TESTIMONIALS = [
  {
    name: 'Priya S.', location: 'Mumbai', dosha: 'Pitta', doshaColor: DOSHA_COLOR.pitta, initials: 'PS',
    quote: 'The dosha quiz completely transformed how I approach eating. My digestion has never been better — I finally understand WHY certain foods affect me the way they do.',
    stars: 5,
  },
  {
    name: 'Arjun M.', location: 'Bengaluru', dosha: 'Vata', doshaColor: DOSHA_COLOR.vata, initials: 'AM',
    quote: 'Ayura AI is the first wellness platform that explains the reasoning behind every recommendation. The adaptive plans saved me months of trial and error.',
    stars: 5,
  },
  {
    name: 'Neha K.', location: 'Delhi', dosha: 'Kapha', doshaColor: DOSHA_COLOR.kapha, initials: 'NK',
    quote: 'The herb safety screening gave me complete peace of mind. As someone on thyroid medication, knowing every recommendation is screened for interactions is invaluable.',
    stars: 5,
  },
]

// ─── Plan showcase ────────────────────────────────────────────
const mix = (v, pct) => `color-mix(in srgb, ${v} ${pct}%, transparent)`
const PLAN_SHOWCASE = [
  { id: 'yoga',        Icon: Flower2,  tint: 'var(--ayura-teal)',    title: 'Yoga & Pranayama',  desc: 'Dosha-balanced morning and evening sequences.', clr: mix('var(--ayura-teal)', 10) },
  { id: 'gym',         Icon: Dumbbell, tint: 'var(--vata-color)',    title: 'Fitness & Gym',      desc: 'Progressive splits with recovery intelligence.', clr: mix('var(--vata-color)', 10) },
  { id: 'diet',        Icon: Salad,    tint: 'var(--ayura-violet)',  title: 'Nutrition Plans',    desc: 'Ayurvedic meal timing with macro precision.', clr: mix('var(--ayura-violet)', 10) },
  { id: 'panchakarma', Icon: Leaf,     tint: 'var(--ayura-emerald)', title: 'Panchakarma Detox', desc: 'Seasonal cleanses calibrated to your prakriti.', clr: mix('var(--ayura-emerald)', 10) },
  { id: 'remedies',    Icon: Soup,     tint: 'var(--ayura-rose)',    title: 'Home Remedies',      desc: 'Kitchen medicine for everyday ailments.', clr: mix('var(--ayura-rose)', 9) },
  { id: 'medicines',   Icon: Pill,     tint: 'var(--ayura-amber)',   title: 'Herbal Medicines',   desc: 'Classical Ayurvedic formulations mapped to you.', clr: mix('var(--ayura-amber)', 10) },
]

// ─── Trust bar items ──────────────────────────────────────────
const TRUST_ITEMS = [
  { Icon: ShieldCheck, label: 'Privacy first' },
  { Icon: Sparkles,    label: 'Gemini AI powered' },
  { Icon: Leaf,        label: 'Ayurveda-verified' },
  { Icon: Zap,         label: 'Free to start' },
]

// ─── Stats strip data ─────────────────────────────────────────
const STATS = [
  { label: 'Plans Generated',  countTo: 5200, suffix: '+' },
  { label: 'Wellness Pillars', countTo: 6 },
  { label: 'Safety Screened',  countTo: 100,  suffix: '%' },
  { label: 'AI Advisor',       static: '24/7' },
]

// ─── Feature Mini-UI Visual components ───────────────────────
const DOSHA_BARS = [
  { label: 'Vata',  cls: 'vata',  color: DOSHA_COLOR.vata,  pct: '65%', val: 65 },
  { label: 'Pitta', cls: 'pitta', color: DOSHA_COLOR.pitta, pct: '45%', val: 45 },
  { label: 'Kapha', cls: 'kapha', color: DOSHA_COLOR.kapha, pct: '30%', val: 30 },
]

function DoshaFeatureVisual() {
  return (
    <div className="lnd-app-preview fmv-fill">
      <div className="lnd-prev-header">
        <span className="lnd-prev-brand">Constitution Analysis</span>
        <span className="lnd-prev-badge" style={{ color: 'var(--vata-color)', background: 'color-mix(in srgb, var(--vata-color) 14%, transparent)', borderColor: 'color-mix(in srgb, var(--vata-color) 30%, transparent)' }}>Vata–Pitta</span>
      </div>
      <div className="lnd-dosha-gauge">
        <div className="lnd-dosha-gauge-title">Dosha Balance</div>
        {DOSHA_BARS.map((d, i) => (
          <div key={d.label} className="lnd-dosha-row">
            <span className="lnd-dosha-label" style={{ color: d.color }}>{d.label}</span>
            <div className="lnd-dosha-bar-track">
              <m.div
                className={`lnd-dosha-bar-fill ${d.cls}`}
                initial={{ width: 0 }}
                whileInView={{ width: d.pct }}
                viewport={{ once: true, amount: 0.5 }}
                transition={{ duration: 1.1, delay: 0.12 * i, ease: [0.16, 1, 0.3, 1] }}
              />
            </div>
            <span className="lnd-dosha-val">{d.val}</span>
          </div>
        ))}
      </div>
      <div className="fmv-insight-chips">
        {['Prakriti: Vata–Pitta', 'Vikriti: Balanced', 'Season: Autumn'].map(chip => (
          <span key={chip} className="fmv-chip">{chip}</span>
        ))}
      </div>
      <div className="fmv-rec-card">
        <span className="fmv-rec-label">Today's Focus</span>
        <p className="fmv-rec-val">Grounding & warmth — reduce Vata with sesame oil, warm root vegetables, and early sleep.</p>
      </div>
    </div>
  )
}

const MINI_PLANS = [
  { Icon: Flower2,  name: 'Yoga',        status: 'ready' },
  { Icon: Dumbbell, name: 'Fitness',     status: 'ready' },
  { Icon: Salad,    name: 'Nutrition',   status: 'ready' },
  { Icon: Leaf,     name: 'Panchakarma', status: 'ready' },
  { Icon: Soup,     name: 'Remedies',    status: 'generating' },
  { Icon: Pill,     name: 'Medicines',   status: 'queued' },
]

function PlansFeatureVisual() {
  return (
    <div className="lnd-app-preview fmv-fill">
      <div className="lnd-prev-header">
        <span className="lnd-prev-brand">Wellness Plans</span>
        <span className="lnd-prev-badge">✦ 4 Ready</span>
      </div>
      <div className="lnd-prev-plans fmv-plans-grid">
        {MINI_PLANS.map(p => (
          <div key={p.name} className={`lnd-prev-plan${p.status === 'generating' ? ' fmv-generating' : ''}`}>
            <div className="lnd-prev-plan-icon"><p.Icon size={20} strokeWidth={1.8} /></div>
            <div className="lnd-prev-plan-name">{p.name}</div>
            <div className={`lnd-prev-plan-status fmv-status-${p.status}`}>
              {p.status === 'ready' ? '✦ Ready' : p.status === 'generating' ? '↻ Crafting…' : '· Queued'}
            </div>
          </div>
        ))}
      </div>
      <div className="fmv-footer-note">✦ AI-generated · adapted to your prakriti daily</div>
    </div>
  )
}

const SAFETY_CHECKS = [
  { herb: 'Ashwagandha', result: 'pass', note: 'No conflicts detected' },
  { herb: 'Triphala',    result: 'pass', note: 'Safe to use' },
  { herb: 'Brahmi',      result: 'pass', note: 'Recommended for Vata' },
  { herb: 'Guggulu',     result: 'warn', note: 'Dosage adjusted' },
  { herb: 'Shatavari',   result: 'pass', note: 'Strengthens immunity' },
]

function SafetyFeatureVisual() {
  return (
    <div className="lnd-app-preview fmv-fill">
      <div className="lnd-prev-header">
        <span className="lnd-prev-brand">Safety Screening</span>
        <span className="lnd-prev-badge" style={{ color: 'var(--ayura-sage)', background: 'color-mix(in srgb, var(--ayura-sage) 12%, transparent)', borderColor: 'color-mix(in srgb, var(--ayura-sage) 28%, transparent)' }}>All Clear</span>
      </div>
      <div className="fmv-check-list">
        {SAFETY_CHECKS.map((item, i) => (
          <m.div
            key={item.herb}
            className="fmv-check-row"
            initial={{ opacity: 0, x: -10 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, amount: 0.4 }}
            transition={{ duration: 0.35, delay: 0.07 * i }}
          >
            <span className={`fmv-check-icon fmv-check-${item.result}`}>
              {item.result === 'pass' ? <Check size={13} strokeWidth={3} /> : <TriangleAlert size={13} strokeWidth={2.5} />}
            </span>
            <div className="fmv-check-info">
              <span className="fmv-check-name">{item.herb}</span>
              <span className="fmv-check-note">{item.note}</span>
            </div>
          </m.div>
        ))}
      </div>
      <div className="fmv-all-clear-badge" style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><ShieldCheck size={15} strokeWidth={2} /> 0 contraindications detected</div>
    </div>
  )
}

// ─── Hero Bento Grid ──────────────
function BentoHeroGrid() {
  return (
    <div className="lnd-hero-visual">
      <m.div
        className="lnd-bento-grid"
        initial={{ opacity: 0, x: 60 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.9, delay: 0.4, ease: [0.16, 1, 0.3, 1] }}
      >
        <m.div
          className="lnd-bento-tile lnd-bento-tile--tall"
          whileHover={{ scale: 1.02, y: -3 }}
          transition={{ type: 'spring', stiffness: 200, damping: 20 }}
        >
          <div className="lnd-bento-tile-kicker">Dosha Intelligence</div>
          <div className="lnd-bento-dosha-rings">
            {[['Vata', DOSHA_COLOR.vata, 65], ['Pitta', DOSHA_COLOR.pitta, 45], ['Kapha', DOSHA_COLOR.kapha, 30]].map(([name, color, val]) => (
              <div key={name} className="lnd-bento-dosha-row">
                <span style={{ color, fontWeight: 700, fontSize: '0.78rem', width: 40 }}>{name}</span>
                <div className="lnd-bento-dosha-track">
                  <m.div
                    className="lnd-bento-dosha-fill"
                    style={{ background: color }}
                    initial={{ width: 0 }}
                    animate={{ width: `${val}%` }}
                    transition={{ duration: 1.3, delay: 0.7, ease: [0.16, 1, 0.3, 1] }}
                  />
                </div>
                <span style={{ color, fontSize: '0.72rem', fontWeight: 700, width: 22 }}>{val}</span>
              </div>
            ))}
          </div>
          <p className="lnd-bento-dosha-note">Vata leads your constitution — lean into warm, grounding routines to stay balanced.</p>
          <div className="lnd-bento-badge">✦ Vata Dominant</div>
        </m.div>
        <m.div
          className="lnd-bento-tile lnd-bento-tile--accent"
          whileHover={{ scale: 1.03, y: -3 }}
          transition={{ type: 'spring', stiffness: 200, damping: 20 }}
        >
          <div className="lnd-bento-tile-icon" style={{ marginBottom: 8 }}><Leaf size={26} strokeWidth={1.6} /></div>
          <div className="lnd-bento-tile-label">Yoga Plan</div>
          <div className="lnd-bento-tile-sub">Ready — updated today</div>
          <div className="lnd-bento-status-dot" />
        </m.div>
        <m.div
          className="lnd-bento-tile lnd-bento-tile--chat"
          whileHover={{ scale: 1.02, y: -3 }}
          transition={{ type: 'spring', stiffness: 200, damping: 20 }}
        >
          <div className="lnd-bento-chat-bubble lnd-bento-chat-bubble--ai">
            What should I eat for Vata balance?
          </div>
          <div className="lnd-bento-chat-bubble lnd-bento-chat-bubble--user">
            Warm, grounding foods — try ghee, sesame & root vegetables.
          </div>
          <div className="lnd-bento-tile-kicker" style={{ marginTop: 8 }}>AI Wellness Advisor</div>
        </m.div>
        <m.div
          className="lnd-bento-tile lnd-bento-tile--stat"
          whileHover={{ scale: 1.03, y: -3 }}
          transition={{ type: 'spring', stiffness: 200, damping: 20 }}
        >
          <div className="lnd-bento-stat-num">360°</div>
          <div className="lnd-bento-stat-lbl">Holistic
Coverage</div>
        </m.div>
      </m.div>
    </div>
  )
}

// ─── FAQ (visible content + must stay in sync with FAQPage JSON-LD in index.html) ───
const FAQS = [
  {
    q: 'What is Ayura AI?',
    a: 'Ayura AI is an AI-powered Ayurvedic wellness platform. It analyses your unique Prakriti (dosha constitution) and builds personalised plans for diet, yoga, Panchakarma, daily routine, and herbal remedies — combining classical Ayurveda with modern AI.',
  },
  {
    q: 'Is Ayura AI free to use?',
    a: 'Yes. You can create an account, take the dosha assessment, and generate personalised wellness plans for free — no credit card required.',
  },
  {
    q: 'What is a dosha or Prakriti?',
    a: 'In Ayurveda your Prakriti is your natural mind-body constitution, made up of three doshas — Vata, Pitta, and Kapha. Ayura AI determines your dominant dosha through a guided assessment and tailors every recommendation to it.',
  },
  {
    q: 'How does Ayura AI personalise my plans?',
    a: 'Ayura AI grounds every plan in a curated Ayurvedic knowledge base and your profile — dosha, age, agni (digestion), season, and any health conditions — then uses AI to turn that into clear, day-by-day guidance for diet, yoga, fitness, detox, and remedies.',
  },
  {
    q: 'Is Ayura AI a substitute for medical advice?',
    a: 'No. Ayura AI provides Ayurvedic wellness guidance for informational and educational purposes only. It does not diagnose, treat, or replace professional medical advice — always consult a qualified practitioner for medical concerns.',
  },
  {
    q: 'Is Ayura AI available in India?',
    a: 'Yes. Ayura AI is built for India and works in any modern web browser on desktop and mobile, with installable progressive web app (PWA) support.',
  },
]

// ─── Main Component ───────────────────────────────────────────
export default function Landing() {
  const { user, logout } = useAuth()
  const [scrolled, setScrolled] = useState(false)
  // On phone-class GPUs the framer transform entrances leave text on stale
  // low-resolution compositor layers — the page LOOKS blurred until something
  // forces a re-raster (verified live: reduced-motion renders razor sharp,
  // animations-on renders soft). So on low-power devices disable transform
  // animations entirely; content simply appears, which also reads faster.
  const lowPower = useLowPowerMode()
  const lenisRef = useRef(null)
  const rafRef   = useRef(null)

  const { scrollY } = useScroll()
  const heroParallaxY       = useTransform(scrollY, [0, 600], [0, -100])
  const heroParallaxOpacity = useTransform(scrollY, [0, 450], [1, 0])

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 30)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  useEffect(() => {
    // Smooth-scroll only on fine-pointer desktops, and never under reduced-motion.
    // On touch (iOS/Android) Lenis fights native momentum + the URL-bar collapse
    // and is a known jank source, so we leave native scrolling alone there.
    if (typeof window === 'undefined' || !window.matchMedia) return
    const fine = window.matchMedia('(hover: hover) and (pointer: fine)')
    const reduce = window.matchMedia('(prefers-reduced-motion: reduce)')
    if (!fine.matches || reduce.matches) return

    const lenis = new Lenis({ duration: 1.2, easing: t => Math.min(1, 1.001 - Math.pow(2, -10 * t)), smoothWheel: true })
    lenisRef.current = lenis
    function raf(time) { lenis.raf(time); rafRef.current = requestAnimationFrame(raf) }
    rafRef.current = requestAnimationFrame(raf)
    return () => { if (rafRef.current) cancelAnimationFrame(rafRef.current); lenis.destroy() }
  }, [])

  useEffect(() => {
    const els = document.querySelectorAll('.reveal, .reveal-left, .reveal-right')
    const obs = new IntersectionObserver(
      entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); obs.unobserve(e.target) } }),
      { threshold: 0.12, rootMargin: '0px 0px -60px 0px' }
    )
    els.forEach(el => obs.observe(el))
    return () => obs.disconnect()
  }, [])

  // Site-wide structured data lives here (not in index.html) so it only renders
  // on the homepage and never leaks onto other prerendered routes like /dosha-test.
  // FAQPage is built from the FAQS array above → schema always matches visible content.
  const siteJsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebSite',
        '@id': 'https://ayuraai.in/#website',
        url: 'https://ayuraai.in',
        name: 'Ayura AI',
        alternateName: ['AyuraAI', 'Ayura', 'Ayura AI App', 'Ayur AI'],
        inLanguage: 'en-IN',
        description: 'AI-Powered Ayurvedic Wellness Platform',
        publisher: { '@id': 'https://ayuraai.in/#organization' },
        potentialAction: {
          '@type': 'SearchAction',
          target: 'https://ayuraai.in/?q={search_term_string}',
          'query-input': 'required name=search_term_string',
        },
      },
      {
        '@type': 'Organization',
        '@id': 'https://ayuraai.in/#organization',
        name: 'Ayura AI',
        alternateName: ['AyuraAI', 'Ayura', 'Ayur AI'],
        url: 'https://ayuraai.in',
        logo: { '@type': 'ImageObject', url: 'https://ayuraai.in/pwa-512x512.png', width: 512, height: 512 },
        image: 'https://ayuraai.in/og-image.png',
        slogan: 'Your wellness, finally in sync — AI + Ayurveda.',
        description: "India's AI-powered Ayurvedic wellness platform providing personalized dosha-based plans for diet, yoga, Panchakarma, and herbal medicine.",
        foundingLocation: { '@type': 'Place', name: 'India' },
        areaServed: { '@type': 'Country', name: 'India' },
        sameAs: [],
      },
      {
        '@type': 'SoftwareApplication',
        '@id': 'https://ayuraai.in/#app',
        name: 'Ayura AI',
        url: 'https://ayuraai.in',
        applicationCategory: 'HealthApplication',
        operatingSystem: 'Web, iOS, Android',
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'INR' },
        description: 'AI-powered Ayurvedic wellness platform for personalized health plans based on Prakriti analysis.',
        screenshot: 'https://ayuraai.in/og-image.png',
      },
      {
        '@type': 'FAQPage',
        '@id': 'https://ayuraai.in/#faq',
        mainEntity: FAQS.map(f => ({
          '@type': 'Question',
          name: f.q,
          acceptedAnswer: { '@type': 'Answer', text: f.a },
        })),
      },
    ],
  }

  return (
    <MotionConfig reducedMotion={lowPower ? 'always' : 'user'}>
    <div className="landing-root">
      <Helmet>
        <title>Ayura AI — AI + Ayurveda Wellness Platform</title>
        <meta name="description" content="Ayura AI blends ancient Ayurvedic wisdom with modern AI to deliver adaptive, personalised wellness plans across fitness, nutrition, detox, and mindfulness." />
        <link rel="canonical" href="https://ayuraai.in" />
        <meta property="og:title" content="Ayura AI — AI-Powered Ayurvedic Wellness" />
        <meta property="og:description" content="India's AI wellness platform rooted in Ayurveda. Personalized plans for diet, yoga, Panchakarma, and herbal medicine based on your dosha." />
        <meta property="og:url" content="https://ayuraai.in" />
        <meta name="twitter:title" content="Ayura AI — AI-Powered Ayurvedic Wellness" />
        <meta name="twitter:description" content="Personalized Ayurvedic diet, yoga, and herbal plans powered by AI. Know your dosha. Live in balance." />
        <script type="application/ld+json">{JSON.stringify(siteJsonLd)}</script>
      </Helmet>

      <CursorGlow />

      {/* ── NAVBAR ──────────────────────────────────────────── */}
      <header className={`lnd-nav-wrap${scrolled ? ' scrolled' : ''}`}>
        <nav className="lnd-nav">
          <Link to="/" className="lnd-brand">
            <div className="lnd-brand-mark-wrap">
              <img src="/favicon.svg" alt="Ayura AI Logo" className="lnd-brand-mark" />
            </div>
            <span className="lnd-brand-text">
              Ayura <span style={{ color: 'var(--ayura-teal)', fontWeight: 800 }}>AI</span>
            </span>
          </Link>
          <div className="lnd-nav-actions">
            {user ? (
              <>
                <Link to="/dashboard" className="lnd-nav-link">Dashboard</Link>
                <button className="lnd-cta-pill" onClick={logout}>Sign out ↗</button>
              </>
            ) : (
              <>
                <Link to="/login" className="lnd-nav-link">Sign In</Link>
                <Link to="/register" className="lnd-cta-pill">Get Started ↗</Link>
              </>
            )}
          </div>
        </nav>
      </header>

      <main>
        {/* ── HERO ────────────────────────────────────────── */}
        <m.section
          className="lnd-hero"
          // MotionValue styles bypass MotionConfig, so gate the parallax layer
          // explicitly — it pins the whole hero onto one GPU layer on phones.
          style={lowPower ? undefined : { y: heroParallaxY, opacity: heroParallaxOpacity }}
        >
          {/* Echo rings behind hero */}
          <div className="lnd-hero-echo" aria-hidden="true">
            <div className="lnd-hero-echo-ring" />
            <div className="lnd-hero-echo-ring" />
            <div className="lnd-hero-echo-ring" />
          </div>
          {/* Left copy */}
          <div className="lnd-hero-copy">
            {/* True page H1 for SEO — keyword/brand-rich, visually hidden so the
                animated tagline below remains the visual focus. */}
            <h1 className="sr-only">Ayura AI — AI-Powered Ayurvedic Wellness Platform</h1>

            <m.span
              className="lnd-hero-kicker"
              initial={PRERENDERED ? false : { opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
            >
              <span className="lnd-hero-kicker-dot" />
              AI + Ayurveda, reimagined
            </m.span>

            {/* Word-by-word stagger (visual tagline, demoted from H1 → H2) */}
            <m.h2
              className="lnd-hero-title"
              variants={stagger}
              initial={PRERENDERED ? false : 'hidden'}
              animate="visible"
            >
              {HERO_WORDS.map((word, i) => (
                <m.span
                  key={i}
                  variants={wordVariants}
                  transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                  style={{
                    display: 'inline-block',
                    marginRight: '0.25em',
                  }}
                >
                  {word === 'sync.' ? <em className="shimmer-text">sync.</em> : word}
                </m.span>
              ))}
            </m.h2>

            {/* Transform-only entrance (opacity stays 1) so this prerendered LCP
                element counts as painted at first paint instead of waiting for a
                fade-in after hydration — big LCP win on slow devices. */}
            <m.p
              className="lnd-hero-subtitle"
              initial={PRERENDERED ? false : { y: 18 }}
              animate={{ y: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
            >
              Ayura AI fuses your unique Ayurvedic constitution with real-time AI to craft adaptive plans across fitness, nutrition, detox, and mindfulness — that evolve with you daily.
            </m.p>

            <m.div
              className="lnd-hero-cta-row"
              initial={PRERENDERED ? false : { opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.28 }}
            >
              {user ? (
                <>
                  <MagneticButton as="a" href="/dashboard" className="lnd-cta-main">Open Dashboard →</MagneticButton>
                  <MagneticButton className="lnd-cta-secondary" onClick={logout}>Switch Account</MagneticButton>
                </>
              ) : (
                <>
                  <MagneticButton as="a" href="/register" className="lnd-cta-main">Create My Profile →</MagneticButton>
                  <MagneticButton as="a" href="#features" className="lnd-cta-secondary">Explore Features</MagneticButton>
                </>
              )}
            </m.div>

            {/* Trust bar */}
            <m.div
              className="lnd-trust-bar"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.4 }}
            >
              {TRUST_ITEMS.map(item => (
                <div key={item.label} className="lnd-trust-item">
                  <span className="lnd-trust-icon"><item.Icon size={13} strokeWidth={2.25} /></span>
                  {item.label}
                </div>
              ))}
            </m.div>
          </div>

          {/* Right visual — Bento grid */}
          <BentoHeroGrid />
        </m.section>

        {/* ── HOW IT WORKS ──────────────────────────────── */}
        <div className="lnd-section">
          <div className="lnd-how-header reveal">
            <span className="lnd-section-kicker">Our Process</span>
            <h2 className="lnd-section-title">How Ayura AI works</h2>
            <p className="lnd-section-desc">
              Three steps from conversation to a living, breathing wellness routine that adapts to who you are today.
            </p>
          </div>

          <div className="lnd-cards-row reveal">
            {HOW_CARDS.map(card => (
              <div key={card.id} className="lnd-how-card">
                <span className="lnd-how-card-step">{card.step}</span>
                <div className="lnd-how-card-icon-badge"><card.Icon size={26} strokeWidth={1.6} /></div>
                <div className="lnd-how-card-body">
                  <div className="lnd-how-card-title">{card.title}</div>
                  <p className="lnd-how-card-desc">{card.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ── STATS STRIP ───────────────────────────── */}
        <div className="lnd-stats-section reveal">
          <div className="lnd-stats-bar">
            {STATS.map(stat => (
              <div key={stat.label} className="lnd-stat">
                <span className="lnd-stat-value">
                  {stat.countTo !== undefined ? (
                    <CountUp
                      to={stat.countTo}
                      suffix={stat.suffix || ''}
                      duration={stat.label === 'Wellness Pillars' ? 900 : 1800}
                    />
                  ) : stat.static}
                </span>
                <span className="lnd-stat-label">{stat.label}</span>
              </div>
            ))}
          </div>
        </div>

        {/* ── FEATURE SECTIONS ────────────────────────── */}
        <div id="features" className="lnd-section" style={{ paddingTop: 0 }}>
          {FEATURES.map((f) => (
            <div key={f.tag} className={`lnd-feature${f.reversed ? ' reverse' : ''}`}>
              <m.div
                className="lnd-feature-copy"
                variants={f.reversed ? fadeRight : fadeLeft}
                initial="hidden"
                whileInView="visible"
                viewport={VP}
                transition={{ duration: 0.7, ease: 'easeOut' }}
              >
                <div className="lnd-feature-icon-wrap"><f.Icon size={26} strokeWidth={1.6} /></div>
                <span className="lnd-section-kicker">{f.tag}</span>
                <h2 className="lnd-feature-title">{f.title}</h2>
                <p className="lnd-feature-desc">{f.desc}</p>
                <ul className="lnd-feature-list">
                  {f.list.map(item => <li key={item}>{item}</li>)}
                </ul>
              </m.div>

              <m.div
                className="lnd-feature-visual"
                variants={f.reversed ? fadeLeft : fadeRight}
                initial="hidden"
                whileInView="visible"
                viewport={VP}
                transition={{ duration: 0.7, ease: 'easeOut', delay: 0.15 }}
              >
                <div className="lnd-feature-img-frame">
                  <f.Visual />
                </div>
              </m.div>
            </div>
          ))}
        </div>

        {/* ── PLAN SHOWCASE ──────────────────────────── */}
        <div className="lnd-section" style={{ paddingTop: 0 }}>
          <div className="reveal" style={{ textAlign: 'center', marginBottom: 0 }}>
            <span className="lnd-section-kicker">Platform Modules</span>
            <h2 className="lnd-section-title">Everything your body needs, in one place.</h2>
            <p className="lnd-section-desc" style={{ margin: '0 auto' }}>
              Six interconnected wellness pillars, each AI-generated and Ayurveda-calibrated for your unique constitution.
            </p>
          </div>

          <div className="lnd-plans-grid reveal">
            {PLAN_SHOWCASE.map((plan) => (
              <m.div
                key={plan.id}
                className="lnd-plan-card"
                style={{ '--plan-clr': plan.clr, '--plan-tint': plan.tint }}
                whileHover={{ y: -4 }}
                transition={{ duration: 0.2 }}
              >
                <span className="lnd-plan-emoji" style={{ color: plan.tint }}>
                  <plan.Icon size={24} strokeWidth={1.7} />
                </span>
                <h3 className="lnd-plan-title">{plan.title}</h3>
                <p className="lnd-plan-desc">{plan.desc}</p>
              </m.div>
            ))}
          </div>
        </div>

        {/* ── TESTIMONIALS ───────────────────────────── */}
        <div className="lnd-section" style={{ paddingTop: 0 }}>
          <div className="reveal" style={{ textAlign: 'center', marginBottom: 48 }}>
            <span className="lnd-section-kicker">User Stories</span>
            <h2 className="lnd-section-title">Trusted by wellness seekers</h2>
          </div>
          <div className="lnd-testimonials-grid reveal">
            {TESTIMONIALS.map(t => (
              <m.div
                key={t.name}
                className="lnd-testimonial-card"
                whileHover={{ y: -4, transition: { duration: 0.2 } }}
              >
                <div className="lnd-testimonial-stars">{'★'.repeat(t.stars)}</div>
                <p className="lnd-testimonial-quote">"{t.quote}"</p>
                <div className="lnd-testimonial-author">
                  <div
                    className="lnd-testimonial-avatar"
                    style={{ background: `${t.doshaColor}22`, border: `1px solid ${t.doshaColor}44`, color: t.doshaColor }}
                  >
                    {t.initials}
                  </div>
                  <div>
                    <div className="lnd-testimonial-name">{t.name}</div>
                    <div className="lnd-testimonial-meta">
                      <span className="lnd-testimonial-dosha" style={{ color: t.doshaColor }}>{t.dosha}</span>
                      <span className="lnd-testimonial-sep">·</span>
                      <span className="lnd-testimonial-loc">{t.location}</span>
                    </div>
                  </div>
                </div>
              </m.div>
            ))}
          </div>
        </div>

        {/* ── FAQ ──────────────────────────────────────── */}
        <div id="faq" className="lnd-section" style={{ paddingTop: 0 }}>
          <div className="reveal" style={{ textAlign: 'center', marginBottom: 40 }}>
            <span className="lnd-section-kicker">Questions</span>
            <h2 className="lnd-section-title">Frequently asked questions</h2>
          </div>
          <div className="lnd-faq-list reveal">
            {FAQS.map((item, i) => (
              <details key={i} className="lnd-faq-item">
                <summary className="lnd-faq-q">
                  <span>{item.q}</span>
                  <span className="lnd-faq-icon" aria-hidden="true">+</span>
                </summary>
                <p className="lnd-faq-a">{item.a}</p>
              </details>
            ))}
          </div>
        </div>

        {/* ── CTA BLOCK ──────────────────────────────── */}
        <div className="lnd-cta-section">
          <m.div
            className="lnd-cta-box"
            variants={fadeUp}
            initial="hidden"
            whileInView="visible"
            viewport={VP}
            transition={{ duration: 0.7 }}
          >
            <h2 className="lnd-cta-box-title">Ready to transform your wellness?</h2>
            <p className="lnd-cta-box-desc">
              Join Ayura AI and experience adaptive health intelligence powered by AI and the timeless science of Ayurveda.
            </p>
            <div className="lnd-cta-box-actions">
              {user ? (
                <Link to="/dashboard" className="lnd-cta-main">Go to Dashboard →</Link>
              ) : (
                <>
                  <MagneticButton as="a" href="/register" className="lnd-cta-main">Start Free — No Card Needed →</MagneticButton>
                  <Link to="/login" className="lnd-cta-secondary">Sign In</Link>
                </>
              )}
            </div>
          </m.div>
        </div>
      </main>

      {/* ── FOOTER ──────────────────────────────────── */}
      <footer className="lnd-footer">
        <div className="lnd-footer-inner">
          <div className="lnd-footer-top">
            <div>
              <Link to="/" className="lnd-footer-brand">
                <img src="/favicon.svg" alt="Ayura AI Logo" className="lnd-footer-brand-mark" />
                <span className="lnd-footer-brand-text">Ayura AI</span>
              </Link>
              <p className="lnd-footer-tagline">
                Redefining wellness through adaptive AI and the timeless science of Ayurveda.
              </p>
            </div>
            <div>
              <p className="lnd-footer-links-title">Platform</p>
              <ul className="lnd-footer-links">
                <li><Link to="/register">Get Started</Link></li>
                <li><Link to="/login">Sign In</Link></li>
                <li><Link to="/dosha-test">Free Dosha Test</Link></li>
                <li><a href="#features">Features</a></li>
              </ul>
            </div>
            <div>
              <p className="lnd-footer-links-title">Legal</p>
              <ul className="lnd-footer-links">
                <li><Link to="/terms">Terms of Service</Link></li>
                <li><Link to="/privacy">Privacy Policy</Link></li>
              </ul>
            </div>
            <div>
              <p className="lnd-footer-links-title">Wellness</p>
              <ul className="lnd-footer-links">
                <li><Link to="/dosha-test">Dosha Test (Vata/Pitta/Kapha)</Link></li>
                <li><a href="#features">Yoga & Fitness</a></li>
                <li><a href="#features">Nutrition Plans</a></li>
                <li><a href="#features">Detox & Remedies</a></li>
              </ul>
            </div>
          </div>
          <div className="lnd-footer-bottom">
            <p className="lnd-footer-copy">© {new Date().getFullYear()} Ayura AI — Adaptive Wellness Platform</p>
            <p className="lnd-footer-disclaimer">
              Ayura AI provides wellness guidance for informational purposes only and does not replace professional medical advice, diagnosis, or treatment.
            </p>
          </div>
        </div>
      </footer>
    </div>
    </MotionConfig>
  )
}
