import { useRef, useEffect, useState, Suspense } from 'react'
import { Link } from 'react-router-dom'
import Lenis from 'lenis'
import { motion, AnimatePresence, useScroll, useTransform } from 'framer-motion'
import { useAuth } from '../providers/AuthContext'
import { Helmet } from 'react-helmet-async'
import React from 'react'
import CursorGlow from '../components/CursorGlow'
import MagneticButton from '../components/MagneticButton'
import CountUp from '../components/CountUp'
import './Landing.css'

// ─── Animation variants ───────────────────────────────────────
const wordVariants = {
  hidden: { opacity: 0, y: 32, filter: 'blur(4px)' },
  visible: { opacity: 1, y: 0, filter: 'blur(0px)' },
}
const stagger = { visible: { transition: { staggerChildren: 0.09 } } }
const fadeUp   = { hidden: { opacity: 0, y: 36 }, visible: { opacity: 1, y: 0 } }
const fadeLeft = { hidden: { opacity: 0, x: -48 }, visible: { opacity: 1, x: 0 } }
const fadeRight= { hidden: { opacity: 0, x:  48 }, visible: { opacity: 1, x: 0 } }
const VP       = { once: true, margin: '-60px' }

// ─── Hero title words ──────────────────────────────────────────
const HERO_WORDS = ['Your', 'wellness,', 'finally', 'in', 'sync.']

// ─── How it works cards ───────────────────────────────────────
const HOW_CARDS = [
  {
    id: 'profile', step: 'Step 01',
    emoji: '🧬',
    title: 'Build Your Dosha Profile',
    desc: 'Answer a deep constitution quiz and our AI maps your Vata, Pitta, Kapha balance into a living health fingerprint.',
  },
  {
    id: 'plans', step: 'Step 02',
    emoji: '🌿',
    title: 'AI Crafts Your Protocol',
    desc: 'Personalised gym, yoga, nutrition, detox, and remedy plans — generated in seconds and recalibrated daily.',
  },
  {
    id: 'sync', step: 'Step 03',
    emoji: '⚡',
    title: 'Adaptive Intelligence, Daily',
    desc: "Check in on energy, mood, and sleep. Plans evolve automatically so you're always in the right zone.",
  },
]

// ─── Feature sections ─────────────────────────────────────────
const FEATURES = [
  {
    tag: 'Dosha Intelligence',
    title: 'Wellness plans that understand your body',
    desc: 'Not generic routines — deeply personalised protocols built from Ayurvedic principles and your unique constitution. Your Vata-Pitta-Kapha balance drives every recommendation.',
    list: ['Prakriti constitution mapping', 'Vikriti imbalance detection', 'Daily adaptive re-scoring'],
    emoji: '🧬',
    stat1: { val: '360°', lbl: 'Holistic coverage' },
    stat2: { val: 'Daily', lbl: 'Plan recalibration' },
    reversed: false,
  },
  {
    tag: 'AI-Powered Plans',
    title: 'Six pillars of health, unified',
    desc: 'Gym splits, yoga flows, Ayurvedic meals, panchakarma detox, home remedies, and herbal formulations — all generated by AI, all tailored to you.',
    list: ['Gym & yoga sequence generation', 'Dosha-matched meal timing', 'Seasonal detox protocols'],
    emoji: '💪',
    stat1: { val: '6', lbl: 'Wellness pillars' },
    stat2: { val: 'AI', lbl: 'Powered engine' },
    reversed: true,
  },
  {
    tag: 'Safety First',
    title: 'Guided by Ayurveda, verified by science',
    desc: 'Every remedy and herbal recommendation passes through a safety layer that screens for contraindications with your medications, allergies, and conditions.',
    list: ['Drug-herb interaction screening', 'Condition-aware filtering', 'Medical disclaimer guardrails'],
    emoji: '🛡️',
    stat1: { val: '100%', lbl: 'Safety checked' },
    stat2: { val: '24/7', lbl: 'AI advisor' },
    reversed: false,
  },
]

// ─── Plan showcase ────────────────────────────────────────────
const PLAN_SHOWCASE = [
  { id: 'yoga',        emoji: '🧘‍♀️', title: 'Yoga & Pranayama',  desc: 'Dosha-balanced morning and evening sequences.', clr: 'rgba(45,212,191,0.10)' },
  { id: 'gym',         emoji: '🏋️',   title: 'Fitness & Gym',      desc: 'Progressive splits with recovery intelligence.', clr: 'rgba(59,130,246,0.10)' },
  { id: 'diet',        emoji: '🥗',   title: 'Nutrition Plans',    desc: 'Ayurvedic meal timing with macro precision.', clr: 'rgba(251,146,60,0.10)' },
  { id: 'panchakarma', emoji: '🌿',   title: 'Panchakarma Detox', desc: 'Seasonal cleanses calibrated to your prakriti.', clr: 'rgba(52,211,153,0.10)' },
  { id: 'remedies',    emoji: '🍵',   title: 'Home Remedies',      desc: 'Kitchen medicine for everyday ailments.', clr: 'rgba(251,113,133,0.08)' },
  { id: 'medicines',   emoji: '💊',   title: 'Herbal Medicines',   desc: 'Classical Ayurvedic formulations mapped to you.', clr: 'rgba(167,139,250,0.10)' },
]

// ─── Trust bar items ──────────────────────────────────────────
const TRUST_ITEMS = [
  { icon: '🔒', label: 'Privacy first' },
  { icon: '🤖', label: 'Gemini AI powered' },
  { icon: '🌿', label: 'Ayurveda-verified' },
  { icon: '⚡', label: 'Free to start' },
]

// ─── Hero Bento Grid ──────────────
function BentoHeroGrid() {
  return (
    <div className="lnd-hero-visual">
      <motion.div
        className="lnd-bento-grid"
        initial={{ opacity: 0, x: 60 }}
        animate={{ opacity: 1, x: 0 }}
        transition={{ duration: 0.9, delay: 0.4, ease: [0.16, 1, 0.3, 1] }}
      >
        <motion.div
          className="lnd-bento-tile lnd-bento-tile--tall"
          whileHover={{ scale: 1.02, y: -3 }}
          transition={{ type: 'spring', stiffness: 200, damping: 20 }}
        >
          <div className="lnd-bento-tile-kicker">Dosha Intelligence</div>
          <div className="lnd-bento-dosha-rings">
            {[['Vata', '#818CF8', 65], ['Pitta', '#fb923c', 45], ['Kapha', '#34d399', 30]].map(([name, color, val]) => (
              <div key={name} className="lnd-bento-dosha-row">
                <span style={{ color, fontWeight: 700, fontSize: '0.78rem', width: 40 }}>{name}</span>
                <div className="lnd-bento-dosha-track">
                  <motion.div
                    className="lnd-bento-dosha-fill"
                    style={{ background: color }}
                    initial={{ width: 0 }}
                    animate={{ width: `${val}%` }}
                    transition={{ duration: 1.3, delay: 0.7, ease: [0.16, 1, 0.3, 1] }}
                  />
                </div>
                <span style={{ color, fontSize: '0.72rem', fontWeight: 700, width: 22 }}>{val}</span>
              </div>
            ))}
          </div>
          <div className="lnd-bento-badge">✦ Vata Dominant</div>
        </motion.div>
        <motion.div
          className="lnd-bento-tile lnd-bento-tile--accent"
          whileHover={{ scale: 1.03, y: -3 }}
          transition={{ type: 'spring', stiffness: 200, damping: 20 }}
        >
          <div style={{ fontSize: '2rem', marginBottom: 8 }}>🌿</div>
          <div className="lnd-bento-tile-label">Yoga Plan</div>
          <div className="lnd-bento-tile-sub">Ready — updated today</div>
          <div className="lnd-bento-status-dot" />
        </motion.div>
        <motion.div
          className="lnd-bento-tile lnd-bento-tile--chat"
          whileHover={{ scale: 1.02, y: -3 }}
          transition={{ type: 'spring', stiffness: 200, damping: 20 }}
        >
          <div className="lnd-bento-chat-bubble lnd-bento-chat-bubble--ai">
            What should I eat for Vata balance?
          </div>
          <div className="lnd-bento-chat-bubble lnd-bento-chat-bubble--user">
            Warm, grounding foods — try ghee, sesame & root vegetables.
          </div>
          <div className="lnd-bento-tile-kicker" style={{ marginTop: 8 }}>AI Wellness Advisor</div>
        </motion.div>
        <motion.div
          className="lnd-bento-tile lnd-bento-tile--stat"
          whileHover={{ scale: 1.03, y: -3 }}
          transition={{ type: 'spring', stiffness: 200, damping: 20 }}
        >
          <div className="lnd-bento-stat-num">360°</div>
          <div className="lnd-bento-stat-lbl">Holistic
Coverage</div>
        </motion.div>
      </motion.div>
    </div>
  )
}

// ─── Main Component ───────────────────────────────────────────
export default function Landing() {
  const { user, logout } = useAuth()
  const [scrolled, setScrolled] = useState(false)
  const lenisRef = useRef(null)
  const rafRef   = useRef(null)
  const heroRef  = useRef(null)

  const { scrollY } = useScroll()
  const heroParallaxY       = useTransform(scrollY, [0, 600], [0, -100])
  const heroParallaxOpacity = useTransform(scrollY, [0, 450], [1, 0])

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 30)
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  useEffect(() => {
    const lenis = new Lenis({ duration: 1.2, easing: t => Math.min(1, 1.001 - Math.pow(2, -10 * t)), smoothWheel: true })
    lenisRef.current = lenis
    function raf(time) { lenis.raf(time); rafRef.current = requestAnimationFrame(raf) }
    rafRef.current = requestAnimationFrame(raf)
    return () => { cancelAnimationFrame(rafRef.current); lenis.destroy() }
  }, [])

  useEffect(() => {
    const els = document.querySelectorAll('.reveal, .reveal-left, .reveal-right')
    const obs = new IntersectionObserver(
      entries => entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); obs.unobserve(e.target) } }),
      { threshold: 0.12, rootMargin: '0px 0px -60px 0px' }
    )
    els.forEach(el => obs.observe(el))
    return () => obs.disconnect()
  }, [])

  return (
    <div className="landing-root">
      <Helmet>
        <title>Ayura AI — AI + Ayurveda Wellness Platform</title>
        <meta name="description" content="Ayura AI blends ancient Ayurvedic wisdom with modern AI to deliver adaptive, personalised wellness plans across fitness, nutrition, detox, and mindfulness." />
      </Helmet>

      <CursorGlow />

      {/* ── NAVBAR ──────────────────────────────────────────── */}
      <header className={`lnd-nav-wrap${scrolled ? ' scrolled' : ''}`}>
        <nav className="lnd-nav">
          <Link to="/" className="lnd-brand">
            <div className="lnd-brand-mark-wrap">
              <img src="/favicon.svg" alt="Ayura AI Logo" className="lnd-brand-mark" />
            </div>
            <span className="lnd-brand-text">
              Ayura <span style={{ color: 'var(--ayura-teal)', fontWeight: 800 }}>AI</span>
            </span>
          </Link>
          <div className="lnd-nav-actions">
            {user ? (
              <>
                <Link to="/dashboard" className="lnd-nav-link">Dashboard</Link>
                <button className="lnd-cta-pill" onClick={logout}>Sign out ↗</button>
              </>
            ) : (
              <>
                <Link to="/login" className="lnd-nav-link">Sign In</Link>
                <Link to="/register" className="lnd-cta-pill">Get Started ↗</Link>
              </>
            )}
          </div>
        </nav>
      </header>

      <main>
        {/* ── HERO ────────────────────────────────────────── */}
        <motion.section
          className="lnd-hero"
          style={{ y: heroParallaxY, opacity: heroParallaxOpacity }}
        >
          {/* Left copy */}
          <div className="lnd-hero-copy">
            <motion.span
              className="lnd-hero-kicker"
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5 }}
            >
              <span className="lnd-hero-kicker-dot" />
              AI + Ayurveda, reimagined
            </motion.span>

            {/* Word-by-word stagger */}
            <motion.h1
              className="lnd-hero-title"
              variants={stagger}
              initial="hidden"
              animate="visible"
            >
              {HERO_WORDS.map((word, i) => (
                <motion.span
                  key={i}
                  variants={wordVariants}
                  transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                  style={{
                    display: 'inline-block',
                    marginRight: '0.25em',
                  }}
                >
                  {word === 'sync.' ? <em className="shimmer-text">sync.</em> : word}
                </motion.span>
              ))}
            </motion.h1>

            <motion.p
              className="lnd-hero-subtitle"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.55 }}
            >
              Ayura AI fuses your unique Ayurvedic constitution with real-time AI to craft adaptive plans across fitness, nutrition, detox, and mindfulness — that evolve with you daily.
            </motion.p>

            <motion.div
              className="lnd-hero-cta-row"
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.7 }}
            >
              {user ? (
                <>
                  <MagneticButton as="a" href="/dashboard" className="lnd-cta-main">Open Dashboard →</MagneticButton>
                  <MagneticButton className="lnd-cta-secondary" onClick={logout}>Switch Account</MagneticButton>
                </>
              ) : (
                <>
                  <MagneticButton as="a" href="/register" className="lnd-cta-main">Create My Profile →</MagneticButton>
                  <MagneticButton as="a" href="#features" className="lnd-cta-secondary">Explore Features</MagneticButton>
                </>
              )}
            </motion.div>

            {/* Trust bar */}
            <motion.div
              className="lnd-trust-bar"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.6, delay: 0.9 }}
            >
              {TRUST_ITEMS.map(item => (
                <div key={item.label} className="lnd-trust-item">
                  <span className="lnd-trust-icon">{item.icon}</span>
                  {item.label}
                </div>
              ))}
            </motion.div>
          </div>

          {/* Right visual — Bento grid */}
          <BentoHeroGrid />
        </motion.section>

        {/* ── HOW IT WORKS ──────────────────────────────── */}
        <div className="lnd-section">
          <div className="lnd-how-header reveal">
            <span className="lnd-section-kicker">Our Process</span>
            <h2 className="lnd-section-title">How Ayura AI works</h2>
            <p className="lnd-section-desc">
              Three steps from conversation to a living, breathing wellness routine that adapts to who you are today.
            </p>
          </div>

          <div className="lnd-cards-row reveal">
            {HOW_CARDS.map(card => (
              <div key={card.id} className="lnd-how-card">
                <span className="lnd-how-card-step">{card.step}</span>
                <div className="lnd-how-card-icon-lg">{card.emoji}</div>
                <div className="lnd-how-card-body">
                  <div className="lnd-how-card-title">{card.title}</div>
                  <p className="lnd-how-card-desc">{card.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* ── FEATURE SECTIONS ────────────────────────── */}
        <div id="features" className="lnd-section" style={{ paddingTop: 0 }}>
          {FEATURES.map((f) => (
            <div key={f.tag} className={`lnd-feature${f.reversed ? ' reverse' : ''}`}>
              <motion.div
                className="lnd-feature-copy"
                variants={f.reversed ? fadeRight : fadeLeft}
                initial="hidden"
                whileInView="visible"
                viewport={VP}
                transition={{ duration: 0.7, ease: 'easeOut' }}
              >
                <div className="lnd-feature-icon-wrap">{f.emoji}</div>
                <span className="lnd-section-kicker">{f.tag}</span>
                <h2 className="lnd-feature-title">{f.title}</h2>
                <p className="lnd-feature-desc">{f.desc}</p>
                <ul className="lnd-feature-list">
                  {f.list.map(item => <li key={item}>{item}</li>)}
                </ul>
              </motion.div>

              <motion.div
                className="lnd-feature-visual"
                variants={f.reversed ? fadeLeft : fadeRight}
                initial="hidden"
                whileInView="visible"
                viewport={VP}
                transition={{ duration: 0.7, ease: 'easeOut', delay: 0.15 }}
              >
                <div className="lnd-feature-img-frame">
                  <div className="lnd-feature-visual-placeholder">{f.emoji}</div>
                  <div className="lnd-mini-stat-card top-right">
                    <div className="lnd-mini-stat-val">{f.stat1.val}</div>
                    <div className="lnd-mini-stat-lbl">{f.stat1.lbl}</div>
                  </div>
                  <div className="lnd-mini-stat-card bottom-left">
                    <div className="lnd-mini-stat-val">{f.stat2.val}</div>
                    <div className="lnd-mini-stat-lbl">{f.stat2.lbl}</div>
                  </div>
                </div>
              </motion.div>
            </div>
          ))}
        </div>

        {/* ── PLAN SHOWCASE ──────────────────────────── */}
        <div className="lnd-section" style={{ paddingTop: 0 }}>
          <div className="reveal" style={{ textAlign: 'center', marginBottom: 0 }}>
            <span className="lnd-section-kicker">Platform Modules</span>
            <h2 className="lnd-section-title">Everything your body needs, in one place.</h2>
            <p className="lnd-section-desc" style={{ margin: '0 auto' }}>
              Six interconnected wellness pillars, each AI-generated and Ayurveda-calibrated for your unique constitution.
            </p>
          </div>

          <div className="lnd-plans-grid reveal">
            {PLAN_SHOWCASE.map((plan) => (
              <motion.div
                key={plan.id}
                className="lnd-plan-card"
                style={{ '--plan-clr': plan.clr }}
                whileHover={{ y: -4 }}
                transition={{ duration: 0.2 }}
              >
                <span className="lnd-plan-emoji">{plan.emoji}</span>
                <h3 className="lnd-plan-title">{plan.title}</h3>
                <p className="lnd-plan-desc">{plan.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>

        {/* ── CTA BLOCK ──────────────────────────────── */}
        <div className="lnd-cta-section">
          <motion.div
            className="lnd-cta-box"
            variants={fadeUp}
            initial="hidden"
            whileInView="visible"
            viewport={VP}
            transition={{ duration: 0.7 }}
          >
            <h2 className="lnd-cta-box-title">Ready to transform your wellness?</h2>
            <p className="lnd-cta-box-desc">
              Join Ayura AI and experience adaptive health intelligence powered by AI and the timeless science of Ayurveda.
            </p>
            <div className="lnd-cta-box-actions">
              {user ? (
                <Link to="/dashboard" className="lnd-cta-main">Go to Dashboard →</Link>
              ) : (
                <>
                  <MagneticButton as="a" href="/register" className="lnd-cta-main">Start Free — No Card Needed →</MagneticButton>
                  <Link to="/login" className="lnd-cta-secondary">Sign In</Link>
                </>
              )}
            </div>
          </motion.div>
        </div>
      </main>

      {/* ── FOOTER ──────────────────────────────────── */}
      <footer className="lnd-footer">
        <div className="lnd-footer-inner">
          <div className="lnd-footer-top">
            <div>
              <Link to="/" className="lnd-footer-brand">
                <img src="/favicon.svg" alt="Ayura AI Logo" className="lnd-footer-brand-mark" />
                <span className="lnd-footer-brand-text">Ayura AI</span>
              </Link>
              <p className="lnd-footer-tagline">
                Redefining wellness through adaptive AI and the timeless science of Ayurveda.
              </p>
            </div>
            <div>
              <p className="lnd-footer-links-title">Platform</p>
              <ul className="lnd-footer-links">
                <li><Link to="/register">Get Started</Link></li>
                <li><Link to="/login">Sign In</Link></li>
                <li><a href="#features">Features</a></li>
              </ul>
            </div>
            <div>
              <p className="lnd-footer-links-title">Wellness</p>
              <ul className="lnd-footer-links">
                <li><a href="#features">Yoga & Fitness</a></li>
                <li><a href="#features">Nutrition Plans</a></li>
                <li><a href="#features">Detox & Remedies</a></li>
              </ul>
            </div>
          </div>
          <div className="lnd-footer-bottom">
            <p className="lnd-footer-copy">© {new Date().getFullYear()} Ayura AI — Adaptive Wellness Platform</p>
            <p className="lnd-footer-disclaimer">
              Ayura AI provides wellness guidance for informational purposes only and does not replace professional medical advice, diagnosis, or treatment.
            </p>
          </div>
        </div>
      </footer>
    </div>
  )
}
