import { Helmet } from 'react-helmet-async'
import { Link } from 'react-router-dom'
import { ArrowLeft } from 'lucide-react'
import './Legal.css'

export default function Terms() {
  return (
    <div className="legal-page">
      <Helmet>
        <title>Terms of Service | Ayura AI</title>
      </Helmet>

      <Link to="/" className="legal-back">
        <ArrowLeft size={16} /> Back to Home
      </Link>

      <div className="legal-header">
        <h1>Terms of Service</h1>
        <p>Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}</p>
      </div>

      <div className="legal-content">
        <div className="legal-important">
          <strong>MEDICAL DISCLAIMER</strong>
          <p style={{ marginBottom: 0, color: 'inherit' }}>
            Ayura AI provides wellness, fitness, and nutritional guidance based on Ayurvedic principles and AI generation for informational and educational purposes only. <strong>The Service is NOT a substitute for professional medical advice, diagnosis, or treatment.</strong> Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Do not disregard professional medical advice or delay in seeking it because of something you have read on Ayura AI.
          </p>
        </div>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using the Ayura AI platform, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          Ayura AI provides AI-generated health, wellness, and fitness plans based on user-provided data, including Ayurvedic dosha profiles. These plans include suggestions for diet, yoga, panchakarma therapies, and home remedies.
        </p>

        <h2>3. User Responsibilities</h2>
        <ul>
          <li>You must provide accurate information when filling out your profile and medical history.</li>
          <li>You are responsible for evaluating your own medical and physical condition and determining whether participating in any diet or exercise program is safe for you.</li>
          <li>If you experience faintness, dizziness, pain, or shortness of breath at any time, you should stop immediately and seek medical help.</li>
          <li>You must not use the service if you are pregnant, nursing, or have a severe medical condition without consulting a healthcare provider first.</li>
        </ul>

        <h2>4. AI-Generated Content</h2>
        <p>
          You acknowledge that the wellness plans and chat responses are generated by Artificial Intelligence. While we strive for accuracy using curated Ayurvedic knowledge bases, AI systems can hallucinate or produce inaccurate information. You agree to use your own judgement before applying any recommendations.
        </p>

        <h2>5. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Ayura AI and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including any bodily injury or health complications resulting from your use of the Service or reliance on any information provided by the Service.
        </p>

        <h2>6. Account Security</h2>
        <p>
          You are responsible for safeguarding your password and you agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.
        </p>
      </div>
    </div>
  )
}
