"""Contraindications, pregnancy suitability and dosha, authored per movement.

These were derived by rule until now — first from keyword matches on the exercise
name, then from the movement's authored mechanism, which was a real improvement
and still not the same as somebody deciding. Writing them out one movement at a
time immediately found faults no rule was going to catch:

  * Every supine press came out `pregnancy_safe: true`. Lying flat on the back is
    ordinarily avoided after the first trimester, and the rule had no concept of
    body position — only of impact, skill and load.
  * `Wall Slide` was withheld from anyone declaring a shoulder problem, because
    the rule saw a vertical-push pattern. It is a scapular rehab drill and one of
    the better things such a person can do.
  * The floor presses were caught by the same rule, when a reduced-range press is
    precisely the pressing option a restricted shoulder keeps.

Each entry carries `why` — the mechanism, in a sentence. That is what turns the
clinical review from an audit into a confirmation: the reviewer reads the reason
and agrees or disagrees with it, rather than reverse-engineering intent from a
list of tags.

**This is still engineering's best reasoning, not clinical sign-off.** Nothing
here has been read by a practitioner. `contraindications_reviewed` stays false
until one does.

Vocabulary is fixed by `schema.CONTRA_VOCAB` — the tokens the engine can act on.
`avoid` is never used for dosha; see `_dosha` in the builder for why.
"""


def C(contra=(), preg=True, vata=None, pitta=None, kapha=None, why=""):
    """One movement's clinical and constitutional judgment.

    Dosha defaults to None rather than "good": a movement only states a dosha
    value here when there is a reason to depart from what its own properties
    imply. Everything else falls through to `_dosha` in the builder, which
    derives from impact, role, pattern and rep style — a systematic reading of
    the classical properties, and a better answer than 173 individual guesses.
    Defaulting them all to "good" silently flattened the field to 81% uniform.
    """
    stated = {k: v for k, v in
              (("vata", vata), ("pitta", pitta), ("kapha", kapha)) if v}
    return {"contra": list(contra), "preg": preg, "why": why, "dosha": stated}


# Shorthands for the restrictions that recur, so a reader can see at a glance
# which mechanism an entry is invoking.
SHOULDER = ["shoulder_injury", "rotator_cuff"]
SPINE = ["herniated_disc", "lower_back_pain"]
KNEE = ["bad_knee", "knee_replacement"]
STRAIN = ["hypertension", "heart_disease"]

CLINICAL: dict[str, dict] = {

    # --------------------------------------------------------------- chest ---
    "Push-Up": C(contra=["wrist_injury"], kapha="good",
                 why="Loaded wrist extension. Trunk stays off the floor, so it is workable in pregnancy for as long as the belly allows."),
    "Knee Push-Up": C(contra=["wrist_injury"],
                      why="As the push-up, with less load through the wrist and shoulder."),
    "Incline Push-Up": C(contra=["wrist_injury"],
                         why="The most prenatal-friendly press: upright, self-limiting, no supine position."),
    "Decline Push-Up": C(contra=["wrist_injury", *SHOULDER], preg=False,
                         why="Head-below-heart position with the shoulder near end range."),
    "Chest Dip": C(contra=[*SHOULDER, "wrist_injury"], preg=False,
                   why="Deep shoulder extension under bodyweight — the position most associated with anterior shoulder strain."),
    "Dip Machine": C(contra=SHOULDER, preg=False,
                     why="Same shoulder position as a dip, with the load chosen rather than fixed."),
    "Barbell Bench Press": C(contra=SHOULDER, preg=False, pitta="moderate",
                             why="Supine, and the heaviest horizontal press available. Lying flat is avoided after the first trimester."),
    "Incline Barbell Bench Press": C(contra=SHOULDER, preg=False, pitta="moderate",
                                     why="Inclined rather than flat, but still a reclined position under a loaded bar."),
    "Dumbbell Bench Press": C(contra=SHOULDER, preg=False,
                              why="Supine. Dumbbells allow a deeper stretch at the bottom than a bar."),
    "Incline Dumbbell Press": C(contra=SHOULDER, preg=False,
                                why="Reclined, and the incline shifts load onto the front of the shoulder."),
    "Barbell Floor Press": C(contra=[], preg=False,
                             why="Supine, so not prenatal — but the floor caps the range, which is why it carries no shoulder restriction: it is the press a restricted shoulder keeps."),
    "Dumbbell Floor Press": C(contra=[], preg=False,
                              why="As above. Deliberately untagged for the shoulder so that someone with a shoulder problem is left with a pressing option."),
    "Machine Bench Press": C(contra=SHOULDER, preg=False,
                             why="Supine and fixed-path; the path is what a restricted shoulder cannot adjust."),
    "Dumbbell Flyes": C(contra=SHOULDER, preg=False,
                        why="Supine, and takes the shoulder to end-range horizontal abduction under load."),
    "Cable Crossover": C(contra=SHOULDER,
                         why="Standing, so no supine restriction, but the same end-range shoulder position as a fly."),
    "Pec Deck": C(contra=SHOULDER,
                  why="Seated and fixed-path at end-range shoulder abduction."),
    "Band Chest Press": C(contra=["shoulder_injury"],
                          why="Upright and light. The mildest press in the library and the one a pregnant practitioner can keep."),

    # ---------------------------------------------------------------- back ---
    "Pull-Up": C(contra=SHOULDER, preg=False,
                 why="Full overhead hang loads the shoulder at end range; hanging is also avoided as the abdomen loads."),
    "Chin-Up": C(contra=SHOULDER, preg=False,
                 why="As the pull-up, with the supinated grip adding elbow load."),
    "Wide-Grip Lat Pulldown": C(contra=SHOULDER,
                                why="Overhead start position. Seated and supported, so no prenatal restriction."),
    "V-Bar Pulldown": C(contra=["shoulder_injury"],
                        why="Neutral close grip is the kindest overhead pull; keeps `shoulder_injury` but not the cuff tag."),
    "Band Lat Pulldown": C(contra=["shoulder_injury"],
                           why="Overhead, but band tension is lowest at the top where the shoulder is most vulnerable."),
    "Bent Over Barbell Row": C(contra=[*SPINE, "hypertension"], preg=False,
                               why="Sustained loaded spinal flexion hold; the hinge position is also unavailable as the abdomen grows."),
    "T-Bar Row": C(contra=SPINE, preg=False,
                   why="Same hinged position as a barbell row."),
    "Bent Over Two-Dumbbell Row": C(contra=SPINE, preg=False,
                                    why="Unsupported hinge under load."),
    "One-Arm Dumbbell Row": C(contra=["lower_back_pain"], preg=False,
                              why="The bench takes most of the spinal load, so the disc restriction is dropped; still a hinged position."),
    "Chest Supported Dumbbell Row": C(contra=[],
                                      why="The bench removes the spinal load entirely. This is the row that survives a back restriction."),
    "Seated Cable Row": C(contra=["lower_back_pain"],
                          why="Seated and supported; the low back still works to hold the torso upright."),
    "Inverted Row": C(contra=[],
                      why="Bodyweight, spine neutral and supported by the feet. Among the safest pulls in the library."),
    "Inverted Row - Underhand Grip": C(contra=["elbow_injury"],
                                       why="As the inverted row; the supinated grip loads the elbow."),
    "Doorway Row": C(contra=[],
                     why="Self-limiting and light — the resistance is your own lean."),
    "Band Row": C(contra=[],
                  why="Upright, light, and fully self-limiting."),
    "Renegade Row": C(contra=[*SHOULDER, "lower_back_pain"], preg=False,
                      why="A plank under a rowing load; the trunk and the supporting shoulder both work hard."),
    "Rack Pull": C(contra=[*SPINE, "hypertension", "osteoporosis"], preg=False,
                   why="Heaviest axial load in the library. Breath-holding against a maximal pull is the mechanism."),
    "Back Extension": C(contra=["herniated_disc"], preg=False, kapha="moderate",
                        why="Repeated lumbar extension. Prone position rules it out prenatally."),
    "Superman Hold": C(contra=SPINE, preg=False, kapha="moderate",
                       why="Sustained lumbar extension, performed lying face down."),
    "Prone Swimmer": C(contra=["lower_back_pain"], preg=False, kapha="moderate",
                       why="Light, but performed face down."),
    "Wall Angel Row": C(contra=[],
                        why="Postural drill against a wall. Suitable for almost everyone, including prenatally."),
    "Straight-Arm Pulldown": C(contra=["shoulder_injury"],
                               why="Long-lever shoulder extension; the straight arm is what makes it a shoulder movement."),
    "Barbell Shrug": C(contra=["cervical_spondylosis", "neck_injury"],
                       why="Heavy load hanging from the shoulder girdle, transmitted through the neck."),
    "Dumbbell Shrug": C(contra=["cervical_spondylosis", "neck_injury"],
                        why="As the barbell shrug."),

    # ----------------------------------------------------------- shoulders ---
    "Barbell Shoulder Press": C(contra=[*SHOULDER, "hypertension"], preg=False,
                                pitta="moderate",
                                why="Overhead pressing with a bar; the bracing required raises intrathoracic pressure."),
    "Dumbbell Shoulder Press": C(contra=SHOULDER,
                                 why="Overhead, but seated and independently loaded so the arms find their own path."),
    "Machine Shoulder Press": C(contra=["shoulder_injury"],
                                why="Supported and fixed-path; suitable when balance rather than the shoulder is the limit."),
    "Arnold Dumbbell Press": C(contra=SHOULDER,
                               why="Adds internal-to-external rotation under load, through the arc the cuff is most exposed in."),
    "Band Overhead Press": C(contra=["shoulder_injury"],
                             why="Overhead, but band tension is lowest at the bottom and the load is small."),
    "Push Press": C(contra=[*SHOULDER, "hypertension", "herniated_disc", "osteoporosis"],
                    preg=False, pitta="moderate", vata="moderate",
                    why="Explosive overhead drive with an axial load and a hard brace."),
    "Upright Row": C(contra=SHOULDER,
                     why="Internal rotation with the arm abducted — the classic impingement position."),
    "Side Lateral Raise": C(contra=["shoulder_injury"],
                            why="Abduction to shoulder height. Light, but directly through the painful arc."),
    "Cable Lateral Raise": C(contra=["shoulder_injury"],
                             why="As the dumbbell version, with tension held at the bottom."),
    "Band Lateral Raise": C(contra=[],
                            why="Lightest abduction available; band tension is least where the arc is most sensitive."),
    "Front Dumbbell Raise": C(contra=["shoulder_injury"],
                              why="Flexion to shoulder height with a long lever."),
    "Bent Over Rear Delt Raise": C(contra=[], preg=False,
                                   why="Posterior shoulder work, which is generally protective. Hinged position rules it out prenatally."),
    "Reverse Flyes": C(contra=[], preg=False,
                       why="As the rear delt raise."),
    "Cable Rear Delt Fly": C(contra=[],
                             why="Standing and upright, so it keeps the posterior work without the hinge."),
    "Face Pull": C(contra=[],
                   why="External rotation with abduction — the movement most often prescribed FOR a shoulder, not against it."),
    "External Rotation": C(contra=[],
                           why="Rotator-cuff rehab loading. Deliberately untagged: withholding it from a shoulder problem removes the treatment."),
    "Band Pull Apart": C(contra=[],
                         why="Scapular retraction against light resistance. Safe for essentially everyone."),
    "Wall Slide": C(contra=[],
                    why="Scapular rehab drill against a wall. The derived rule withheld it from shoulder problems, which is backwards."),
    "Arm Circles": C(contra=[], kapha="moderate",
                     why="Unloaded joint preparation."),
    "Pike Push-Up": C(contra=[*SHOULDER, "wrist_injury"], preg=False,
                      why="Bodyweight overhead press with the head below the heart."),
    "Hands-Elevated Pike Push-Up": C(contra=["shoulder_injury", "wrist_injury"],
                                     why="Less overhead load and less inversion than the floor version."),
    "Pike Push-Up - Feet Elevated": C(contra=[*SHOULDER, "wrist_injury", "hypertension"],
                                      preg=False,
                                      why="Near-vertical loading with the head well below the heart."),
    "Wall Handstand Hold": C(contra=[*SHOULDER, "wrist_injury", "hypertension"], preg=False,
                             vata="moderate",
                             why="Full inversion under bodyweight; blood pressure and wrist load are both at their limit."),
    "Prone T-Raise": C(contra=[], preg=False, kapha="moderate",
                       why="Light posterior shoulder work, performed face down."),
    "Prone Y-Raise": C(contra=[], preg=False, kapha="moderate",
                       why="As the T-raise, with more shoulder flexion."),
    "Plank Shoulder Tap": C(contra=["wrist_injury"], preg=False,
                            why="Loaded wrist extension in a plank; the plank position is unavailable as the abdomen loads."),

    # -------------------------------------------------------------- biceps ---
    "Barbell Curl": C(contra=["elbow_injury"],
                      why="Fixed supinated grip gives the elbow and wrist no room to adjust."),
    "EZ-Bar Curl": C(contra=["elbow_injury"],
                     why="The angled bar eases the wrist; the elbow load is unchanged."),
    "Preacher Curl": C(contra=["elbow_injury"],
                       why="Loads the elbow at full extension, where the joint is least protected."),
    "Dumbbell Bicep Curl": C(contra=[],
                             why="Free rotation lets the wrist and elbow find a comfortable path."),
    "Hammer Curls": C(contra=[],
                      why="Neutral grip is the most forgiving curl for the elbow and wrist."),
    "Concentration Curls": C(contra=["elbow_injury"],
                             why="Braced arm removes the escape route the standing versions allow."),
    "Standing Dumbbell Reverse Curl": C(contra=["elbow_injury"],
                                        why="Pronated grip loads the lateral elbow — the tennis-elbow mechanism."),
    "Cable Curl": C(contra=["elbow_injury"],
                    why="Constant tension holds the elbow under load through the whole range."),
    "Cable Hammer Curl": C(contra=[],
                           why="Neutral grip with constant tension; the kindest loaded curl."),
    "Band Biceps Curl": C(contra=[],
                          why="Tension is lowest at full extension, where the elbow is most exposed."),
    "Self-Resisted Biceps Curl": C(contra=[],
                                   why="The practitioner sets the resistance, so it cannot exceed what they tolerate."),
    "Towel Biceps Curl": C(contra=[],
                           why="As above — self-limiting by construction."),

    # ------------------------------------------------------------- triceps ---
    "Close-Grip Bench Press": C(contra=["elbow_injury", *SHOULDER], preg=False,
                                why="Supine press; the narrow grip concentrates load at the elbow."),
    "Lying Triceps Press": C(contra=["elbow_injury"], preg=False,
                             why="Supine, and loads the elbow at end-range flexion."),
    "EZ-Bar Skullcrusher": C(contra=["elbow_injury"], preg=False,
                             why="As above, with the angled bar easing the wrist only."),
    "Triceps Pushdown": C(contra=["elbow_injury"],
                          why="Standing and self-limiting, but the elbow is the working joint."),
    "One-Arm Cable Pushdown": C(contra=["elbow_injury"],
                                why="As the pushdown, one side at a time."),
    "Band Triceps Pushdown": C(contra=[],
                               why="Lightest elbow extension available."),
    "Standing Dumbbell Triceps Extension": C(contra=["elbow_injury", "shoulder_injury"],
                                             why="Overhead position stretches the long head and loads the shoulder to hold it there."),
    "Dumbbell Overhead Triceps Extension - Two Hands": C(contra=["elbow_injury", "shoulder_injury"],
                                                         why="As above; two hands make it steadier, not lighter on the shoulder."),
    "Triceps Overhead Extension with Rope": C(contra=["elbow_injury", "shoulder_injury"],
                                              why="Overhead under constant cable tension."),
    "Tricep Dumbbell Kickback": C(contra=[],
                                  why="Short lever, light load, elbow working in mid-range."),
    "Bench Dips": C(contra=[*SHOULDER, "wrist_injury"], preg=False,
                    why="Internally rotated shoulder behind the torso — a poor position under load."),
    "Close-Grip Push-Up": C(contra=["wrist_injury", "elbow_injury"],
                            why="Loaded wrist extension with the elbows tracking close."),
    "Diamond Push-Up": C(contra=["wrist_injury", "elbow_injury"], preg=False,
                         why="The narrowest hand position puts the wrist at its end range."),
    "Incline Close-Grip Push-Up": C(contra=["wrist_injury"],
                                    why="Elevated hands reduce both the load and the wrist angle."),
    "Bodyweight Triceps Extension": C(contra=["elbow_injury", "wrist_injury"],
                                      why="Self-limiting, but the elbow is the only joint working."),
}

CLINICAL.update({

    # ---------------------------------------------------------------- legs ---
    "Barbell Squat": C(contra=[*KNEE, "herniated_disc", "hypertension", "osteoporosis"],
                       preg=False, pitta="moderate",
                       why="Axial load through the spine with a hard brace; the knee is at end-range flexion under that load."),
    "Front Barbell Squat": C(contra=[*KNEE, "shoulder_injury", "herniated_disc", "osteoporosis"],
                             preg=False, pitta="moderate",
                             why="As the back squat, plus a rack position the shoulder and wrist must hold."),
    "Hack Squat": C(contra=KNEE, preg=False,
                    why="Fixed path holds the knee in one line whether or not that is the practitioner's line."),
    "Leg Press": C(contra=["bad_knee", "herniated_disc"], preg=False,
                   why="Deep knee flexion under heavy load; the low back rounds off the pad at depth."),
    "Goblet Squat": C(contra=["bad_knee"],
                      why="The chest-held weight keeps the torso upright and the load light. The squat that survives most restrictions."),
    "Bodyweight Squat": C(contra=["bad_knee"],
                          why="No external load; depth is self-selected."),
    "Box Squat to a Chair": C(contra=[],
                              why="The chair sets the depth, so the knee never passes into an unmanaged range."),
    "Banded Squat": C(contra=["bad_knee"],
                      why="Band tension is highest standing and lowest at depth, which is the opposite of where the knee is loaded."),
    "Wall Sit": C(contra=["bad_knee"], kapha="moderate",
                  why="Sustained isometric knee flexion; the position is fixed and the load is bodyweight."),
    "Barbell Deadlift": C(contra=[*SPINE, "hypertension", "osteoporosis"], preg=False,
                          pitta="moderate",
                          why="The heaviest axial pull available, with a brace held against a maximal effort."),
    "Sumo Deadlift": C(contra=[*SPINE, "hypertension", "osteoporosis", "hip_injury"], preg=False,
                       pitta="moderate",
                       why="As the conventional pull, with the wide stance loading the hip in abduction."),
    "Barbell Romanian Deadlift": C(contra=[*SPINE, "hypertension"], preg=False,
                                   why="Sustained loaded hinge; the hamstrings run out before the spine does, which is where it goes wrong."),
    "Dumbbell Romanian Deadlift": C(contra=SPINE, preg=False,
                                    why="Same hinge, lighter load, dumbbells tracking closer to the body."),
    "Banded Romanian Deadlift": C(contra=["lower_back_pain"],
                                  why="Lightest hinge in the library; tension is lowest at the bottom where the spine is most flexed."),
    "Good Morning": C(contra=[*SPINE, "hypertension", "osteoporosis"], preg=False,
                      why="Bar on the back through a hinge — the longest lever against the spine of anything here."),
    "Barbell Hip Thrust": C(contra=["lower_back_pain"], preg=False,
                            why="Spine stays neutral and supported, so the disc restriction is dropped; the low back still resists extension at the top."),
    "Glute Bridge": C(contra=[], preg=False,
                      why="Supine, which rules it out after the first trimester. Otherwise among the gentlest hip movements."),
    "Single Leg Glute Bridge": C(contra=["lower_back_pain"], preg=False,
                                 why="Supine, and the single-leg version asks the low back to resist rotation."),
    "Glute Bridge March": C(contra=["lower_back_pain"], preg=False,
                            why="Supine bridge held while the trunk resists tilt."),
    "Band Pull-Through": C(contra=["lower_back_pain"],
                           why="Hinge pattern with the load pulling backwards rather than down — the least spinal compression of any hinge."),
    "Glute Kickback": C(contra=["lower_back_pain"],
                        why="Quadruped position; the low back arches if the range is chased."),
    "Barbell Lunge": C(contra=[*KNEE, "osteoporosis"], preg=False,
                       why="Loaded single-leg work with a bar on the back — balance fails before the muscles do."),
    "Dumbbell Lunges": C(contra=KNEE, preg=False,
                         why="Single-leg knee flexion under load; the dumbbells can be dropped, which the bar cannot."),
    "Reverse Lunge": C(contra=["bad_knee"],
                       why="Stepping back rather than forward keeps the front shin vertical and is markedly kinder to the knee."),
    "Split Squat": C(contra=["bad_knee"],
                     why="Both feet planted, so the balance demand is low and the knee path is stable."),
    "Bulgarian Split Squat": C(contra=KNEE, preg=False,
                               why="Deep single-leg flexion with the rear foot elevated; a demanding position for the front knee."),
    "Dumbbell Step Ups": C(contra=KNEE,
                           why="Loaded single-leg knee extension; box height decides how much."),
    "Barbell Step Ups": C(contra=[*KNEE, "osteoporosis"], preg=False,
                          why="As above with an axial load and a balance demand on top."),
    "Leg Extensions": C(contra=KNEE,
                        why="Open-chain knee extension puts shear through the joint that closed-chain work does not."),
    "Lying Leg Curls": C(contra=["bad_knee"], preg=False,
                         why="Prone position rules it out prenatally; hamstring loading at the knee otherwise."),
    "Seated Leg Curl": C(contra=["bad_knee"],
                         why="Seated and supported, so it keeps the hamstring work without the prone position."),
    "Standing Calf Raise": C(contra=["bad_ankle"],
                             why="Full ankle range under bodyweight."),
    "Seated Calf Raise": C(contra=["bad_ankle"],
                           why="Bent knee moves the work to the soleus; ankle range is the same."),
    "Calf Raises - With Bands": C(contra=[],
                                  why="Lightest ankle loading available."),
    "Kettlebell Swing": C(contra=[*SPINE, "hypertension"], preg=False, vata="moderate",
                          why="Ballistic hinge; the spine decelerates the bell at the bottom of every rep."),
    "90/90 Hamstring": C(contra=[], kapha="moderate",
                         why="Passive stretch against a wall, range self-selected."),
    "Adductor": C(contra=["hip_injury"], kapha="moderate",
                  why="End-range hip abduction; the load is the weight of the legs."),
    "Lying Prone Quadriceps": C(contra=["bad_knee"], preg=False, kapha="moderate",
                                why="End-range knee flexion, performed lying face down."),
    "Seated Glute": C(contra=["hip_injury"], kapha="moderate",
                      why="Passive hip external rotation with a forward hinge."),
    "Standing Hip Circles": C(contra=[], kapha="moderate",
                              why="Unloaded joint preparation through the hip's own range."),

    # ---------------------------------------------------------------- core ---
    "Plank": C(contra=["lower_back_pain"], preg=False,
               why="The trunk resists extension against gravity — a demand that rises sharply as the abdomen loads."),
    "Side Plank": C(contra=["shoulder_injury"], preg=False,
                    why="The supporting shoulder carries the bodyweight."),
    "Dead Bug": C(contra=[], preg=False,
                  why="Supine. One of the better trunk drills for a sensitive back, since the range is set by the back staying flat."),
    "Bird Dog": C(contra=[],
                  why="Quadruped, low load, spine neutral. Safe for essentially everyone, including prenatally."),
    "Hollow Body Hold": C(contra=SPINE, preg=False,
                          why="Supine with a long lever; the low back lifts the moment the trunk gives."),
    "Crunches": C(contra=SPINE, preg=False,
                  why="Repeated loaded spinal flexion. Abdominal separation makes this unsuitable prenatally."),
    "Exercise Ball Crunch": C(contra=SPINE, preg=False,
                              why="As the crunch, through a longer range."),
    "Cable Crunch": C(contra=SPINE, preg=False,
                      why="Weighted spinal flexion — the highest-load flexion movement in the library."),
    "Lying Leg Raise": C(contra=SPINE, preg=False,
                         why="Supine with a long lever; the low back arches as soon as the abdominals are outmatched."),
    "Hanging Leg Raise": C(contra=[*SHOULDER, "lower_back_pain"], preg=False,
                           why="Hanging loads the shoulder throughout; the pelvis must tilt before the legs move."),
    "Leg Raise on Parallel Bars": C(contra=["shoulder_injury", "lower_back_pain"], preg=False,
                                    why="Supported on the forearms, so less shoulder load than hanging."),
    "Russian Twist": C(contra=SPINE, preg=False,
                       why="Loaded rotation of a flexed spine — the position discs tolerate least."),
    "Standing Cable Wood Chop": C(contra=["lower_back_pain"], preg=False,
                                  why="Rotation under load, though driven from the hips rather than the lumbar spine."),
    "Dumbbell Side Bend": C(contra=SPINE, preg=False,
                            why="Loaded lateral flexion of the lumbar spine."),
    "Pallof Press": C(contra=[],
                      why="Anti-rotation: the trunk resists movement rather than producing it. Safe prenatally and with most back restrictions."),
    "Ab Wheel Rollout": C(contra=[*SPINE, "shoulder_injury"], preg=False,
                          why="The longest anti-extension lever there is, with the shoulders holding the position."),
    "Exercise Ball Pull-In": C(contra=["lower_back_pain", "shoulder_injury"], preg=False,
                               why="Plank on an unstable base; the shoulders support throughout."),
    "Farmer's Walk": C(contra=["cervical_spondylosis", "neck_injury"],
                       why="Load hangs from the shoulder girdle through the neck; the spine itself stays neutral and braced."),
    "Suitcase Carry": C(contra=["lower_back_pain", "cervical_spondylosis"],
                        why="One-sided load the trunk resists laterally."),

    # -------------------------------------------------------------- cardio ---
    "Brisk Walking": C(contra=[],
                       why="The most universally available conditioning there is. No restriction in the library excludes it."),
    "Incline Treadmill Walk": C(contra=["bad_knee"], kapha="good",
                                why="Walking mechanics with the incline raising the effort rather than the impact."),
    "Stationary Cycling": C(contra=["bad_knee"],
                            why="Non-impact and fully supported; resistance is chosen."),
    "Elliptical Trainer": C(contra=[],
                            why="Supported, non-impact, and among the better prenatal options. **Flagged for review** — the merged duplicate said otherwise."),
    "Rowing Machine": C(contra=[*SPINE, "lower_back_pain"], preg=False,
                        why="Repeated loaded hinge at high cadence, where form fails as fatigue arrives."),
    "Swimming": C(contra=[],
                  why="Non-weight-bearing. Survives essentially every musculoskeletal restriction."),
    "Stair Climbing": C(contra=KNEE,
                        why="Repeated single-leg knee extension under bodyweight."),
    "Jump Rope": C(contra=[*STRAIN, *KNEE, "bad_ankle"], preg=False, vata="moderate",
                   why="Repetitive landing impact at high frequency."),
    "High Knees": C(contra=[*STRAIN, "bad_knee"], preg=False, vata="moderate",
                    why="Running mechanics in place; landing force through knee and ankle."),
    "Jumping Jacks": C(contra=[*KNEE, "bad_ankle"], preg=False, vata="moderate",
                       why="Repeated bilateral landing with the arms overhead."),
    "Mountain Climbers": C(contra=[*STRAIN, "shoulder_injury"], preg=False,
                           why="Plank position held under a cardiovascular load; shoulders support throughout."),
    "Burpees": C(contra=[*STRAIN, *KNEE, "shoulder_injury"], preg=False,
                 vata="moderate", pitta="moderate",
                 why="Maximal-effort whole-body work combining landing impact with a floor transition."),
    "Sprint Intervals (HIIT)": C(contra=[*STRAIN, *KNEE], preg=False,
                                 vata="moderate", pitta="moderate",
                                 why="Near-maximal cardiovascular effort with running impact."),
    "HIIT Circuit": C(contra=[*STRAIN, "bad_knee"], preg=False,
                      vata="moderate", pitta="moderate",
                      why="Sustained high effort with form degrading as the circuit progresses."),
    "Air Bike": C(contra=STRAIN, preg=False, pitta="moderate",
                  why="Self-limiting and non-impact, but the effort ceiling is as high as anything here."),
    "Battle Ropes": C(contra=[*STRAIN, "shoulder_injury"], preg=False,
                      why="Sustained shoulder work at a cardiovascular intensity."),

    # ------------------------------------------------------ mobility / warm ---
    "Cat-Cow": C(contra=[], kapha="moderate",
                 why="Unloaded spinal movement through a self-selected range. Suitable prenatally."),
    "Child's Pose": C(contra=["bad_knee"], kapha="moderate",
                      why="Deep knee flexion in the kneeling position; the spine is unloaded."),
    "Inchworm": C(contra=["lower_back_pain", "wrist_injury"], kapha="moderate",
                  why="Loaded forward fold into a plank; the wrists carry bodyweight at the far end."),
    "Wrist Circles": C(contra=[], kapha="moderate",
                       why="Unloaded joint preparation."),
})
