"""Bodyweight and band movements for the practitioner training at home.

The old library held 141 bodyweight entries and 42 of them were abdominal work,
against five for the lats and three for the mid back — so a home user's back day
was three prone raises and the same wall drill every session. Bands get their own
attention here because they are the cheapest way to make a home upper body
trainable, and the import had twenty of them in total.
"""

from .spec import M

HOME = [
    # ---- bands: pressing and pulling --------------------------------------
    M("Band Chest Press", src=None, bucket="chest", pattern="push_h",
      mechanic="compound", equipment="bands", role="main",
      skill_floor="beginner", level="beginner", family="bench_press",
      pm=["chest"], sm=["triceps", "shoulders"],
      instructions=[
          "Anchor a resistance band behind you at chest height, or run it across your upper back.",
          "Hold an end in each hand with the elbows bent and the hands beside the chest.",
          "Press both hands forward until the arms are straight, bringing the hands slightly together.",
          "Pause, then return under control until the hands are back beside the chest.",
      ],
      cue="Step further from the anchor to make it harder — that is your weight stack.",
      easier="step closer to the anchor",
      harder="Dumbbell Bench Press"),

    M("Band Row", src=None, bucket="back", pattern="pull_h", mechanic="compound",
      equipment="bands", role="main", skill_floor="beginner", level="beginner",
      family="bodyweight_row", pm=["middle back"], sm=["lats", "biceps"],
      instructions=[
          "Anchor a band at chest height, or sit on the floor and loop it around your feet.",
          "Hold an end in each hand with the arms extended and the shoulders back.",
          "Pull both hands to the ribs by driving the elbows straight back.",
          "Squeeze the shoulder blades together for a beat, then extend the arms under control.",
      ],
      cue="Elbows past the ribs, chest tall. Do not let the shoulders round forward at the end.",
      easier="step closer to the anchor",
      harder="Inverted Row"),

    M("Band Lat Pulldown", src=None, bucket="back", pattern="pull_v",
      mechanic="compound", equipment="bands", role="accessory",
      skill_floor="beginner", level="beginner", family="pulldown",
      pm=["lats"], sm=["biceps", "middle back"],
      instructions=[
          "Anchor a band overhead — a door anchor or a sturdy bar both work.",
          "Kneel or sit below it and hold an end in each hand with the arms overhead.",
          "Pull the hands down and out toward the shoulders, driving the elbows toward the ribs.",
          "Control the band back overhead until the arms are straight again.",
      ],
      cue="The closest a home setup gets to a pulldown. Keep the torso still.",
      easier="a lighter band, or kneel further from the anchor",
      harder="Pull-Up"),

    M("Band Overhead Press", src=None, bucket="shoulders", pattern="push_v",
      mechanic="compound", equipment="bands", role="main",
      skill_floor="beginner", level="beginner", family="overhead_press",
      pm=["shoulders"], sm=["triceps"],
      instructions=[
          "Stand on the middle of a resistance band with the feet hip-width apart.",
          "Hold an end in each hand at shoulder height with the palms facing forward.",
          "Brace the trunk and press both hands overhead until the arms are straight.",
          "Lower back to shoulder height under control, resisting the band on the way down.",
      ],
      cue="Ribs down. If the low back arches to finish the press, the band is too strong.",
      easier="a lighter band",
      harder="Dumbbell Shoulder Press"),

    M("Band Lateral Raise", src="Lateral Raise - With Bands", bucket="shoulders",
      pattern="isolation", mechanic="isolation", equipment="bands",
      role="accessory", skill_floor="beginner", level="beginner",
      family="lateral_raise",
      cue="Slow on the way down — bands make the lowering half the useful half.",
      easier="a lighter band",
      harder="Side Lateral Raise"),

    M("Band Biceps Curl", src=None, bucket="biceps", pattern="isolation",
      mechanic="isolation", equipment="bands", role="accessory",
      skill_floor="beginner", level="beginner", family="curl",
      pm=["biceps"], sm=["forearms"],
      instructions=[
          "Stand on the middle of a resistance band with the feet hip-width apart.",
          "Hold an end in each hand with the arms at your sides and the palms facing forward.",
          "Curl both hands toward the shoulders, keeping the elbows pinned to your sides.",
          "Lower slowly against the band's pull until the arms are straight.",
      ],
      cue="Bands get harder as you curl, which is exactly where the biceps is strongest.",
      easier="a lighter band",
      harder="Dumbbell Bicep Curl"),

    M("Band Triceps Pushdown", src=None, bucket="triceps", pattern="isolation",
      mechanic="isolation", equipment="bands", role="accessory",
      skill_floor="beginner", level="beginner", family="pushdown",
      pm=["triceps"], sm=[],
      instructions=[
          "Anchor a band overhead and hold an end in each hand.",
          "Stand tall with the elbows tucked at your sides and bent to about ninety degrees.",
          "Push the hands down until the arms are straight, keeping the elbows still.",
          "Let the band draw the hands back up under control.",
      ],
      cue="Only the forearms move. If the elbows travel, drop the tension.",
      easier="a lighter band",
      harder="Triceps Pushdown"),

    M("Band Pull-Through", src="Band Good Morning (Pull Through)", bucket="legs",
      pattern="hinge", mechanic="compound", equipment="bands", role="accessory",
      skill_floor="beginner", level="beginner", family="hip_thrust",
      contra=["lower_back_pain"],
      cue="Hips drive back and then forward; the band should brush the inner thighs.",
      easier="a lighter band",
      harder="Barbell Hip Thrust"),

    # ---- bodyweight upper body, where the old library ran out --------------
    M("Doorway Row", src=None, bucket="back", pattern="pull_h",
      mechanic="compound", equipment="bodyweight", role="accessory",
      skill_floor="beginner", level="beginner", family="bodyweight_row", unilateral=True,
      pm=["middle back"], sm=["lats", "biceps"],
      instructions=[
          "Stand facing a sturdy door frame and take hold of it at chest height with one hand.",
          "Place the feet either side of the frame, close to it, and lean back with the arm straight.",
          "Pull yourself upright by driving the elbow back, keeping the body in one line.",
          "Lower back to a straight arm under control, then change sides.",
      ],
      cue="No bar, no band, still a real row. Walk the feet forward to make it harder.",
      easier="stand more upright, feet closer to the frame",
      harder="Inverted Row"),

    M("Towel Biceps Curl", src=None, bucket="biceps", pattern="isolation",
      mechanic="isolation", equipment="bodyweight", role="accessory",
      skill_floor="beginner", level="beginner", family="curl", unilateral=True,
      pm=["biceps"], sm=["forearms"],
      instructions=[
          "Stand on one end of a towel and hold the other end in one hand, palm up.",
          "Keep the elbow pinned to your side and curl the hand toward the shoulder.",
          "Push down through the foot to resist as you curl, making the movement hard.",
          "Lower slowly under the same resistance, then change sides.",
      ],
      cue="You set the resistance with the foot — make the last two reps a genuine fight.",
      easier="Self-Resisted Biceps Curl",
      harder="Band Biceps Curl"),

    M("Pike Push-Up - Feet Elevated", src=None, bucket="shoulders",
      pattern="push_v", mechanic="compound", equipment="bodyweight",
      role="accessory", skill_floor="advanced", level="advanced",
      family="overhead_press", contra=["shoulder_injury", "hypertension"],
      pm=["shoulders"], sm=["triceps"],
      instructions=[
          "Set the feet on a box or a chair and walk the hands back until the hips are stacked high.",
          "Place the hands slightly wider than the shoulders with the fingers spread.",
          "Lower the crown of the head toward the floor between the hands.",
          "Press back to straight arms, keeping the hips high throughout.",
      ],
      cue="The closest a home setup gets to an overhead press with real load.",
      easier="Pike Push-Up",
      harder="Wall Handstand Hold"),

    M("Wall Slide", src=None, bucket="shoulders", pattern="push_v",
      mechanic="isolation", equipment="bodyweight", role="warmup",
      skill_floor="beginner", level="beginner", family="wall_angel",
      pm=["shoulders"], sm=["middle back", "traps"],
      instructions=[
          "Stand with your back against a wall and the feet a few inches out from it.",
          "Place the forearms on the wall with the elbows at shoulder height.",
          "Slide the arms up the wall as far as you can without the low back arching away.",
          "Slide back down slowly, keeping the forearms in contact throughout.",
      ],
      cue="Best two minutes you can spend before pressing anything overhead."),

    M("Glute Bridge March", src=None, bucket="core", pattern="anti_extension",
      mechanic="compound", equipment="bodyweight", role="accessory",
      skill_floor="beginner", level="beginner", family="hip_thrust",
      unilateral=True, pm=["abdominals"], sm=["glutes", "hamstrings"],
      instructions=[
          "Lie on your back with the knees bent and the feet flat on the floor.",
          "Press through the heels to lift the hips into a bridge and hold them there.",
          "Without letting the hips drop or tilt, lift one knee toward the chest.",
          "Return that foot to the floor and repeat on the other side, alternating throughout.",
      ],
      cue="The hips must not dip when the foot leaves the floor. That is the whole test.",
      easier="Glute Bridge",
      harder="Single Leg Glute Bridge"),

    # ---- closing the last thin cells ---------------------------------------
    M("Cable Hammer Curl", src="Cable Hammer Curls - Rope Attachment",
      bucket="biceps", pattern="isolation", mechanic="isolation",
      equipment="cable", role="accessory", load_class="hammer_curl",
      skill_floor="beginner", level="beginner", family="hammer_curl",
      instructions=[
          "Attach a rope to a low pulley and stand about a foot-length back from the machine.",
          "Take an end of the rope in each hand with the palms facing one another and the elbows at your sides.",
          "Curl the hands toward the shoulders, keeping the elbows pinned and the wrists neutral.",
          "Squeeze at the top and pull the ends of the rope slightly apart.",
          "Lower under control against the cable until the arms are straight.",
      ],
      cue="Neutral grip on the rope, and pull the ends apart at the top."),

    M("One-Arm Cable Pushdown", src="Cable One Arm Tricep Extension",
      bucket="triceps",
      pattern="isolation", mechanic="isolation", equipment="cable",
      role="accessory", load_class="triceps_pushdown", skill_floor="beginner",
      level="beginner", family="pushdown", unilateral=True,
      cue="One side at a time finds the weaker arm quickly."),

    M("Exercise Ball Crunch", bucket="core", pattern="isolation",
      mechanic="isolation", equipment="other", role="accessory",
      skill_floor="beginner", level="beginner", family="crunch",
      contra=["herniated_disc", "lower_back_pain"],
      cue="The ball lets the spine extend past flat, which is the point of using it."),

    M("Exercise Ball Pull-In", bucket="core", pattern="anti_extension",
      mechanic="compound", equipment="other", role="accessory",
      skill_floor="intermediate", level="intermediate", family="pull_in",
      cue="Start in a plank with the shins on the ball and keep the hips from piking."),
    M("Hands-Elevated Pike Push-Up", src=None, bucket="shoulders",
      pattern="push_v", mechanic="compound", equipment="bodyweight",
      role="main", skill_floor="beginner", level="beginner",
      family="overhead_press", pm=["shoulders"], sm=["triceps", "chest"],
      instructions=[
          "Place the hands on a bench, chair or low table and walk the feet back.",
          "Push the hips up and back until the torso and arms form a straight line.",
          "Bend the elbows to lower the head toward the raised surface between the hands.",
          "Press back up to straight arms, keeping the hips high the whole time.",
      ],
      cue="Hands high makes it easier. This is where an overhead press starts with no equipment.",
      harder="Pike Push-Up"),

    M("Plank Shoulder Tap", src=None, bucket="shoulders", pattern="anti_rotation",
      mechanic="compound", equipment="bodyweight", role="accessory",
      skill_floor="beginner", level="beginner", family="shoulder_tap",
      unilateral=True, pm=["shoulders"], sm=["abdominals", "chest"],
      instructions=[
          "Start in a push-up position with the hands under the shoulders and the feet wide.",
          "Brace the trunk so the hips are level and square to the floor.",
          "Lift one hand and tap the opposite shoulder without letting the hips rotate.",
          "Return the hand to the floor and repeat on the other side, alternating throughout.",
      ],
      cue="Widen the feet if the hips twist. Not rotating is the work.",
      easier="widen the feet, or drop to the knees",
      harder="Plank Shoulder Tap with the feet together"),

    M("Prone T-Raise", src=None, bucket="shoulders", pattern="isolation",
      mechanic="isolation", equipment="bodyweight", role="accessory",
      skill_floor="beginner", level="beginner", family="prone_raise",
      pm=["shoulders"], sm=["middle back"],
      instructions=[
          "Lie face down with the arms out to the sides at shoulder height, forming a T.",
          "Turn the thumbs up toward the ceiling.",
          "Lift both arms by squeezing the shoulder blades together.",
          "Hold briefly at the top, then lower slowly without resting the hands down.",
      ],
      cue="Rear delts and mid-back. Small range, done properly, beats a big sloppy one.",
      harder="Prone Y-Raise"),
    M("Incline Close-Grip Push-Up", src="Incline Push-Up Close-Grip",
      bucket="triceps", pattern="push_h", mechanic="compound",
      equipment="bodyweight", role="main", skill_floor="beginner",
      level="beginner", family="push_up", contra=["wrist_injury"],
      cue="Hands close and elevated — the triceps push-up a beginner can actually do.",
      harder="Close-Grip Push-Up"),

    M("Bodyweight Triceps Extension", src=None, bucket="triceps",
      pattern="isolation", mechanic="isolation", equipment="bodyweight",
      role="accessory", skill_floor="beginner", level="beginner",
      family="triceps_extension", pm=["triceps"], sm=["abdominals"],
      instructions=[
          "Set your hands shoulder-width apart on a bench, low bar or sturdy table edge.",
          "Walk the feet back so the body is straight and leaning into the surface.",
          "Keeping the upper arms still and pointing forward, bend only the elbows to lower the forehead toward your hands.",
          "Press back to straight arms by extending the elbows, without letting the hips sag.",
      ],
      cue="Only the elbows move. Walk the feet back to make it harder, in toward the surface to make it easier.",
      easier="walk the feet in toward the surface",
      harder="Diamond Push-Up"),
]
