"""Instruction prose for every movement, written for this product.

Kept apart from `movements_*.py` on purpose: those files are the SPEC — a few
lines per movement stating what it is and how it may be programmed, which is what
a reviewer reads. This is bulk content. Separating them keeps both readable, and
makes it checkable at a glance that no instruction text comes from a dataset.

Why it was rewritten. 120 movements reused free-exercise-db's prose and 89 of
them carried at least one defect:

  * `Dumbbell Romanian Deadlift` opened "Put a barbell in front of you on the
    ground" — the wrong implement, in the step that sets the exercise up.
  * Two entries instructed the reader to HOLD THEIR BREATH under load. The engine
    tags `hypertension` precisely for breath-holding strain and withholds those
    movements from anyone over 60; the instructions were teaching the mechanism
    the safety model exists to avoid.
  * Three carried imperial measurements spelled out ("step backwards two feet"),
    under the digit-matching guard.
  * 66 said "This will be your starting position", 57 closed with "repeat for the
    recommended amount of repetitions" — above which the app has already printed
    the sets and reps — and 50 had inline "Tip:" artifacts.

House style, applied to all of them:

  * four to six steps: set up, execute, return, and the boundary that decides the
    range — the sentence that tells you when to stop rather than how far to go
  * second person, imperative, present tense
  * metric only
  * no breath-holding under load; breathe out on the effort or not at all
  * no closing rep instruction — the prescription is printed above the steps
"""

INSTRUCTIONS: dict[str, list[str]] = {

    # ---------------------------------------------------------------- back ---
    "Back Extension": [
        "Set yourself in a back-extension bench with the pads just below the hip bones.",
        "Cross the arms over the chest and let the torso hang, keeping the spine long.",
        "Squeeze the glutes and raise the torso until the body forms one straight line.",
        "Stop at that line — lifting past it arches the low back and is where this goes wrong.",
        "Lower under control until you feel the hamstrings and low back lengthen.",
    ],
    "Barbell Shrug": [
        "Stand tall holding a barbell at arm's length in front of the thighs, hands shoulder-width apart.",
        "Set the shoulders back and keep the arms completely straight throughout.",
        "Lift the shoulders straight up toward the ears as far as they will travel.",
        "Pause for a full second at the top — the traps respond to the hold, not the bounce.",
        "Lower slowly until the shoulders are fully relaxed down.",
    ],
    "Bent Over Barbell Row": [
        "Stand with the feet hip-width apart and hold a barbell with an overhand grip just outside the knees.",
        "Push the hips back and hinge forward to roughly 45 degrees, keeping the spine long and the knees soft.",
        "Let the bar hang at arm's length, then pull it to the navel by driving the elbows back.",
        "Squeeze the shoulder blades together at the top without letting the torso rise to meet the bar.",
        "Lower the bar under control until the arms are straight and the shoulder blades travel forward.",
    ],
    "Bent Over Two-Dumbbell Row": [
        "Hold a dumbbell in each hand and stand with the feet hip-width apart.",
        "Hinge forward from the hips to about 45 degrees with the spine long and the knees slightly bent.",
        "Let both dumbbells hang beneath the shoulders with the palms facing in.",
        "Row them to the ribs by driving the elbows back and past the torso.",
        "Lower under control to straight arms, holding the back angle steady the whole time.",
    ],
    "Chest Supported Dumbbell Row": [
        "Set an incline bench to about 45 degrees and lie chest-down on it with the feet braced.",
        "Hold a dumbbell in each hand with the arms hanging straight down, palms facing in.",
        "Pull the shoulder blades together first, then row both dumbbells to the ribs.",
        "Pause at the top with the elbows past the torso.",
        "Lower slowly to straight arms — the bench holds your position, so the back does all the work.",
    ],
    "Chin-Up": [
        "Take an underhand grip on a bar, hands roughly shoulder-width apart.",
        "Hang at full arm extension with the shoulders pulled down away from the ears.",
        "Pull the elbows down to the ribs until the chin clears the bar.",
        "Keep the ribs down and avoid swinging the legs to generate momentum.",
        "Lower under control all the way to straight arms.",
    ],
    "Dumbbell Shrug": [
        "Stand tall with a dumbbell hanging at each side, palms facing the thighs.",
        "Set the shoulders back and keep the arms straight and relaxed.",
        "Raise both shoulders straight up toward the ears as high as they will go.",
        "Hold for a second at the top, then lower slowly.",
        "Move straight up and down — rolling the shoulders adds nothing but wear.",
    ],
    "One-Arm Dumbbell Row": [
        "Place one knee and the same-side hand on a bench, with the other foot on the floor.",
        "Hold a dumbbell in the free hand with the arm hanging straight down.",
        "Keep the torso square to the floor and the spine long.",
        "Row the dumbbell to the hip, not the shoulder, driving the elbow past the ribs.",
        "Lower under control to a full stretch, then complete the set before changing sides.",
    ],
    "Pull-Up": [
        "Take an overhand grip on a bar slightly wider than the shoulders.",
        "Hang at full arm extension and pull the shoulders down away from the ears.",
        "Drive the elbows down toward the ribs until the chest approaches the bar.",
        "Keep the body still — a swing turns this into a different exercise.",
        "Lower slowly to straight arms before the next repetition.",
    ],
    "Rack Pull": [
        "Set the safety pins in a rack at about knee height and rest a loaded barbell on them.",
        "Stand with the feet hip-width apart, shins against the bar, and take an overhand grip outside the knees.",
        "Set the chest up and the spine long, then drive through the floor to stand tall.",
        "Finish with the hips and knees locked and the shoulders back, without leaning backwards.",
        "Lower the bar to the pins under control rather than dropping it.",
    ],
    "Renegade Row": [
        "Start in a push-up position with a hand on each dumbbell, feet wider than the hips for balance.",
        "Brace the trunk hard so the hips stay level and square to the floor.",
        "Row one dumbbell to the ribs while pressing the other firmly into the ground.",
        "Refuse to let the hips rotate — if they do, widen the feet or go lighter.",
        "Lower the dumbbell under control and repeat on the other side.",
    ],
    "Seated Cable Row": [
        "Sit at the machine with the feet braced and take the handle with the arms extended.",
        "Sit tall with a long spine and a slight forward lean at the start.",
        "Pull the handle to the navel by driving the elbows back past the ribs.",
        "Squeeze the shoulder blades together, then extend the arms slowly.",
        "Let the shoulder blades travel forward at the end of each rep rather than holding them locked.",
    ],
    "Straight-Arm Pulldown": [
        "Stand facing a high pulley with a straight bar attached, feet hip-width apart.",
        "Take an overhand grip and step back about half a metre until the arms are extended overhead.",
        "Hinge forward slightly from the hips, keeping the elbows just short of locked.",
        "Keeping the arms long, pull the bar down in an arc until it reaches the thighs.",
        "Return along the same arc under control — the moment the elbows bend, it becomes a pushdown.",
    ],
    "V-Bar Pulldown": [
        "Sit at a pulldown machine with the thighs secured under the pads.",
        "Take a close neutral grip on the V-handle with the arms extended overhead.",
        "Lean the torso back no more than about 15 degrees and keep it there.",
        "Pull the handle to the upper chest by driving the elbows down toward the ribs.",
        "Return slowly to full arm extension, letting the shoulder blades rise at the top.",
    ],
    "Wide-Grip Lat Pulldown": [
        "Sit at a pulldown machine and secure the thighs under the pads.",
        "Take an overhand grip on the bar noticeably wider than the shoulders, arms extended overhead.",
        "Set the chest up and lean back only slightly, keeping that angle for the whole set.",
        "Pull the bar to the collarbone by driving the elbows down and out, not by leaning further back.",
        "Return to full extension under control, allowing the shoulder blades to travel up.",
    ],

    # -------------------------------------------------------------- biceps ---
    "Barbell Curl": [
        "Stand tall holding a barbell with an underhand grip, hands about shoulder-width apart.",
        "Let the bar hang at arm's length with the elbows tucked against the ribs.",
        "Curl the bar toward the chest, keeping the elbows pinned in place.",
        "Squeeze at the top, then lower slowly until the arms are straight.",
        "If the elbows drift forward or the hips swing, the weight is too heavy.",
    ],
    "Cable Curl": [
        "Attach a straight bar to a low pulley and stand about a foot-length back from the machine.",
        "Take an underhand grip and let the arms hang straight with the elbows at your sides.",
        "Curl the bar toward the shoulders without letting the elbows travel forward.",
        "Squeeze at the top, where cable tension is highest.",
        "Lower under control against the pull until the arms are fully straight.",
    ],
    "Cable Hammer Curl": [
        "Attach a rope to a low pulley and stand about a foot-length back from the machine.",
        "Take an end of the rope in each hand with the palms facing one another.",
        "Keep the elbows pinned to the sides and curl both hands toward the shoulders.",
        "At the top, pull the ends of the rope slightly apart and hold for a beat.",
        "Lower slowly against the cable until the arms are straight.",
    ],
    "Concentration Curls": [
        "Sit on the end of a bench with the feet wide and a dumbbell in one hand.",
        "Brace the back of that upper arm against the inside of the same-side thigh.",
        "Let the arm hang straight, then curl the dumbbell toward the shoulder.",
        "Turn the palm up as you lift and squeeze at the top.",
        "Lower slowly to a straight arm, then finish the set before changing sides.",
    ],
    "Dumbbell Bicep Curl": [
        "Stand tall with a dumbbell in each hand hanging at arm's length, palms facing in.",
        "Tuck the elbows against the ribs and keep them there throughout.",
        "Curl the weights up, turning the palms to face the ceiling as you lift.",
        "Squeeze at the top with the dumbbells at shoulder height.",
        "Lower slowly, reversing the rotation, until the arms are straight.",
    ],
    "EZ-Bar Curl": [
        "Stand tall holding an EZ-bar on the inner angled grips, palms facing up and forward.",
        "Let the bar hang at arm's length with the elbows against the ribs.",
        "Curl the bar toward the chest without letting the elbows move forward.",
        "Squeeze at the top, then lower under control to straight arms.",
        "The angled grip sits the wrists in a more comfortable position than a straight bar.",
    ],
    "Hammer Curls": [
        "Stand tall with a dumbbell in each hand, palms facing your thighs.",
        "Keep the elbows tucked at your sides and the wrists neutral throughout.",
        "Curl both dumbbells toward the shoulders without rotating the palms.",
        "Pause briefly at the top.",
        "Lower slowly to straight arms — the neutral grip works the forearm as much as the biceps.",
    ],
    "Preacher Curl": [
        "Set the preacher bench so the top of the pad sits under the armpits when seated.",
        "Rest the backs of both upper arms flat on the pad and take an underhand grip on the bar.",
        "Curl the bar toward the shoulders, keeping the arms in contact with the pad.",
        "Squeeze at the top, then lower slowly.",
        "Stop just short of a locked elbow at the bottom — slamming into full extension is what the elbow objects to.",
    ],
    "Standing Dumbbell Reverse Curl": [
        "Stand tall with a dumbbell in each hand and the palms facing your thighs, knuckles forward.",
        "Keep the elbows tucked and the wrists straight and firm.",
        "Curl both dumbbells toward the shoulders with the palms staying down.",
        "Pause at the top without letting the wrists collapse backwards.",
        "Lower slowly to straight arms — go lighter than a normal curl, the forearm is the limit here.",
    ],

    # --------------------------------------------------------------- chest ---
    "Barbell Bench Press": [
        "Lie on a flat bench with the eyes under the bar and the feet flat on the floor.",
        "Pull the shoulder blades together and down into the bench and keep them there.",
        "Grip the bar a little wider than the shoulders and unrack it over the chest.",
        "Lower the bar to the mid-chest with the elbows about 45 degrees from the body.",
        "Press back up until the arms are straight, keeping the shoulder blades set.",
    ],
    "Barbell Floor Press": [
        "Lie on the floor beneath a barbell in a rack set low, knees bent and feet flat.",
        "Grip the bar a little wider than the shoulders and unrack it over the chest.",
        "Lower until the backs of the upper arms rest on the floor.",
        "Pause there for a beat rather than bouncing off the ground.",
        "Press back to straight arms — the floor caps the range, which is what makes this shoulder-friendly.",
    ],
    "Cable Crossover": [
        "Set both pulleys above head height and take a handle in each hand.",
        "Step forward into a split stance with the arms out wide and the elbows softly bent.",
        "Bring the hands down and together in front of the hips in a wide arc.",
        "Squeeze the chest with the hands together, keeping the elbow angle fixed.",
        "Return along the same arc under control until you feel the chest lengthen.",
    ],
    "Chest Dip": [
        "Take hold of parallel bars and press up to straight arms with the feet crossed behind.",
        "Lean the torso forward about 30 degrees and let the elbows travel out slightly.",
        "Lower until the upper arms are roughly parallel to the floor.",
        "Stop there — going deeper puts the shoulder in its most vulnerable position.",
        "Press back to straight arms, keeping the forward lean throughout.",
    ],
    "Decline Push-Up": [
        "Set the feet on a bench or step and place the hands slightly wider than the shoulders on the floor.",
        "Press up until the arms are straight and the body forms one line from head to heels.",
        "Lower the chest toward the floor with the elbows angled back rather than flared wide.",
        "Press back to straight arms without letting the hips sag.",
        "The higher the feet, the more the load shifts to the upper chest and shoulders.",
    ],
    "Dip Machine": [
        "Set the seat so the handles sit level with the lower chest, and select the assistance or load.",
        "Sit tall, take the handles, and set the shoulders down away from the ears.",
        "Press down until the arms are straight, keeping a slight forward lean.",
        "Return under control until the upper arms are roughly parallel to the floor.",
        "This is the assisted version of a dip — use it to build toward the real thing.",
    ],
    "Dumbbell Bench Press": [
        "Sit on the end of a flat bench with a dumbbell resting on each thigh.",
        "Lie back, using the thighs to help bring the dumbbells to either side of the chest.",
        "Set the shoulder blades together and down, with the wrists stacked over the elbows.",
        "Press both dumbbells up over the mid-chest until the arms are straight.",
        "Lower slowly until the upper arms are level with the torso, taking about twice as long as the press.",
    ],
    "Dumbbell Floor Press": [
        "Lie on the floor with the knees bent and a dumbbell in each hand at the chest.",
        "Set the shoulder blades down and the wrists stacked over the elbows.",
        "Press both dumbbells straight up until the arms lock out over the chest.",
        "Lower until the backs of the upper arms touch the floor, then pause a beat.",
        "Press again from that dead stop rather than bouncing off the ground.",
    ],
    "Dumbbell Flyes": [
        "Lie on a flat bench holding a dumbbell in each hand directly above the chest, palms facing in.",
        "Set a slight bend in the elbows and keep that angle fixed for the whole set.",
        "Open the arms out in a wide arc until the chest lengthens and the elbows are level with the torso.",
        "Stop there rather than chasing depth — the shoulder, not the chest, is what gives first.",
        "Bring the dumbbells back together along the same arc, squeezing the chest at the top.",
    ],
    "Incline Barbell Bench Press": [
        "Set a bench to about 30 degrees and lie back with the feet flat on the floor.",
        "Pull the shoulder blades together and down and grip the bar a little wider than the shoulders.",
        "Unrack the bar and hold it over the upper chest with straight arms.",
        "Lower it to just below the collarbone with the elbows angled back.",
        "Press back to straight arms — steeper than 30 degrees hands the set to the front shoulder.",
    ],
    "Incline Dumbbell Press": [
        "Set a bench to about 30 degrees and sit back with a dumbbell resting on each thigh.",
        "Lie back and bring the dumbbells to either side of the upper chest.",
        "Set the shoulder blades down and the wrists stacked over the elbows.",
        "Press both dumbbells up until the arms are straight above the upper chest.",
        "Lower slowly until the upper arms are level with the torso.",
    ],
    "Incline Push-Up": [
        "Place the hands slightly wider than the shoulders on a bench, step or sturdy table.",
        "Walk the feet back until the body is one straight line from head to heels.",
        "Lower the chest toward the surface with the elbows angled about 45 degrees from the ribs.",
        "Press back to straight arms without letting the hips sag or pike.",
        "The higher the surface, the easier it is — lower it as you get stronger.",
    ],
    "Machine Bench Press": [
        "Set the seat so the handles sit level with the mid-chest when you sit down.",
        "Sit back with the whole spine against the pad and the feet flat on the floor.",
        "Take the handles and set the shoulder blades down away from the ears.",
        "Press forward until the arms are straight, without letting the shoulders round forward.",
        "Return slowly until the hands are level with the chest.",
    ],
    "Pec Deck": [
        "Set the seat so the handles sit level with the shoulders when seated.",
        "Sit back against the pad and take a handle in each hand with the elbows level with the shoulders.",
        "Bring the arms together in front of the chest in a smooth arc.",
        "Squeeze for a beat with the hands close together.",
        "Open the arms back to the start under control, stopping when the chest lengthens.",
    ],
    "Push-Up": [
        "Lie face down and set the hands slightly wider than the shoulders, level with the mid-chest.",
        "Tuck the toes under and press up until the arms are straight and the body forms one line.",
        "Lower under control until the chest is a few centimetres off the floor.",
        "Keep the elbows angled about 45 degrees from the ribs rather than flared straight out.",
        "Press the floor away to return to straight arms, squeezing the glutes to stop the hips sagging.",
    ],
}

INSTRUCTIONS.update({

    # ---------------------------------------------------------------- legs ---
    "90/90 Hamstring": [
        "Lie on your back beside a doorway or wall with one leg flat on the floor.",
        "Raise the other leg and rest the heel against the wall with the hip and knee both bent to 90 degrees.",
        "Slowly straighten that knee until you feel the hamstring lengthen.",
        "Hold there and breathe — ease off the moment it turns sharp.",
        "Bend the knee to release, then change sides.",
    ],
    "Adductor": [
        "Sit on the floor and bring the soles of the feet together, letting the knees fall out to the sides.",
        "Hold the ankles and sit tall through the spine.",
        "Ease the knees toward the floor using the weight of the legs rather than forcing them.",
        "Hold and breathe, keeping the back long rather than rounding over.",
        "Bring the knees back together with the hands to come out of it.",
    ],
    "Band Pull-Through": [
        "Anchor a resistance band at ankle height and stand facing away from it.",
        "Reach between the legs and take the band in both hands, then step forward to build tension.",
        "Push the hips back, letting the hands travel between the thighs with a long spine.",
        "Drive the hips forward to stand tall, squeezing the glutes at the top.",
        "Finish with the ribs down rather than leaning back.",
    ],
    "Barbell Deadlift": [
        "Stand with the feet hip-width apart and the bar over the middle of the feet, shins nearly touching it.",
        "Push the hips back and take an overhand grip just outside the knees.",
        "Set the chest up, flatten the back and take the slack out of the bar before pulling.",
        "Drive through the floor with the legs, keeping the bar against the legs the whole way up.",
        "Finish standing tall with the hips locked, then push the hips back to lower it along the same path.",
    ],
    "Barbell Hip Thrust": [
        "Sit on the floor with the upper back against a bench and a padded barbell across the hips.",
        "Set the feet flat, about shoulder-width apart, with the shins vertical at the top of the movement.",
        "Tuck the chin and keep the ribs down, then drive through the heels to lift the hips.",
        "Finish with the hips level with the knees and the glutes squeezed hard.",
        "Lower under control without letting the low back take over from the glutes.",
    ],
    "Barbell Lunge": [
        "Set a barbell across the upper back as you would for a squat and stand tall.",
        "Take a controlled step forward, roughly two-thirds of a metre.",
        "Lower until both knees are bent to about 90 degrees and the front shin is close to vertical.",
        "Drive through the front heel to return to standing.",
        "Balance is the limit here rather than strength — go lighter than you think you need.",
    ],
    "Barbell Romanian Deadlift": [
        "Stand tall holding a barbell at arm's length against the thighs, hands just outside the knees.",
        "Set the knees softly bent and hold that bend throughout — this is a hinge, not a squat.",
        "Push the hips back and let the bar travel down the front of the legs, keeping the spine long.",
        "Stop when the hamstrings run out of length, usually around mid-shin.",
        "Drive the hips forward to stand tall, keeping the bar against the legs the whole way.",
    ],
    "Barbell Squat": [
        "Set the bar across the upper back, not the neck, and grip it firmly with the elbows down.",
        "Step back and set the feet shoulder-width apart with the toes turned slightly out.",
        "Brace the trunk as if about to be punched in the stomach.",
        "Sit down and back between the hips, keeping the chest up and the knees tracking over the middle toes.",
        "Descend to at least parallel if your hips allow it, then drive the floor away to stand.",
    ],
    "Barbell Step Ups": [
        "Set a box at or just below knee height and place a barbell across the upper back.",
        "Stand facing the box and place one whole foot on it.",
        "Drive through that heel to stand up on the box, keeping the torso upright.",
        "Step down under control with the other foot, resisting the drop.",
        "Complete the reps on one side before changing, and keep the box below knee height.",
    ],
    "Bodyweight Squat": [
        "Stand with the feet about shoulder-width apart and the toes turned slightly out.",
        "Reach the arms forward for balance and set the chest up.",
        "Sit down and back between the hips as though reaching for a low chair.",
        "Keep the heels down and the knees tracking over the middle toes.",
        "Descend as far as you can hold the position, then drive through the heels to stand tall.",
    ],
    "Calf Raises - With Bands": [
        "Sit or stand with the balls of the feet on the floor and a resistance band over the thighs or under the feet.",
        "Take up the slack so there is tension before you move.",
        "Press through the balls of the feet to raise the heels as high as they will go.",
        "Hold the top position for a full second.",
        "Lower slowly until the heels are back down — calves answer to time under tension, not to bouncing.",
    ],
    "Dumbbell Lunges": [
        "Stand tall with a dumbbell hanging at each side and the feet hip-width apart.",
        "Take a controlled step forward, roughly two-thirds of a metre.",
        "Lower until both knees are bent to about 90 degrees, keeping the front shin close to vertical.",
        "Drive through the front heel to push back to standing.",
        "Keep the torso upright and let the dumbbells hang still rather than swinging.",
    ],
    "Dumbbell Romanian Deadlift": [
        "Stand tall with a dumbbell in each hand resting against the front of the thighs.",
        "Set the knees softly bent and keep that bend for the whole set.",
        "Push the hips back and let the dumbbells travel down the front of the legs.",
        "Keep the spine long and the dumbbells in contact with the legs throughout.",
        "Stop when the hamstrings run out of length, then drive the hips forward to stand tall.",
    ],
    "Dumbbell Step Ups": [
        "Set a box at or just below knee height and hold a dumbbell in each hand.",
        "Place one whole foot on the box, heel included.",
        "Drive through that heel to stand up, keeping the torso upright and the dumbbells hanging.",
        "Step down under control with the trailing foot — that is the half everyone rushes.",
        "Complete the reps on one side before changing.",
    ],
    "Front Barbell Squat": [
        "Rack the bar across the front of the shoulders and raise the elbows until the upper arms are parallel to the floor.",
        "Step back and set the feet shoulder-width apart with the toes slightly out.",
        "Brace hard and keep the elbows high — the moment they drop, the bar follows.",
        "Sit straight down with an upright torso, knees tracking over the middle toes.",
        "Drive through the whole foot to stand, keeping the elbows up all the way.",
    ],
    "Glute Bridge": [
        "Lie on your back with the knees bent and the feet flat, about hip-width apart.",
        "Set the arms at your sides and tuck the pelvis so the low back flattens.",
        "Drive through the heels to lift the hips until the body forms one line from knees to shoulders.",
        "Squeeze the glutes at the top with the ribs down, not with the low back arched.",
        "Lower under control until the hips just touch the floor.",
    ],
    "Glute Kickback": [
        "Start on hands and knees with the wrists under the shoulders and the knees under the hips.",
        "Brace the trunk so the low back stays flat and the hips stay square.",
        "Keeping one knee bent at 90 degrees, drive that heel toward the ceiling.",
        "Stop when the thigh is level with the torso — going higher arches the low back.",
        "Lower under control and complete the reps before changing sides.",
    ],
    "Goblet Squat": [
        "Hold a dumbbell or kettlebell vertically against the chest with both hands under the top of it.",
        "Set the feet shoulder-width apart with the toes turned slightly out.",
        "Keep the elbows tucked in and the chest tall — the weight at the chest is what keeps you upright.",
        "Sit down between the hips, letting the elbows travel inside the knees.",
        "Drive through the whole foot to stand, keeping the weight against the chest throughout.",
    ],
    "Good Morning": [
        "Set a light barbell across the upper back and stand with the feet hip-width apart.",
        "Soften the knees and brace the trunk hard.",
        "Push the hips back and hinge the torso forward with the spine long.",
        "Stop as soon as the hamstrings tighten or the back begins to round — the honest range here is short.",
        "Drive the hips forward to stand tall, and use far less weight than feels necessary.",
    ],
    "Hack Squat": [
        "Set yourself in the machine with the back flat against the pad and the shoulders under the supports.",
        "Place the feet shoulder-width apart in the middle of the platform.",
        "Release the safeties and lower by bending the knees, keeping the whole back on the pad.",
        "Descend until the thighs are roughly parallel, or until the low back starts to lift.",
        "Drive through the whole foot to press back up without locking the knees hard at the top.",
    ],
    "Leg Extensions": [
        "Sit in the machine with the back against the pad and the knee joint level with the machine's pivot.",
        "Set the ankle pad just above the top of the feet.",
        "Straighten both legs until the knees are extended, without snapping into the lockout.",
        "Pause for a second at the top and squeeze the thighs.",
        "Lower slowly under control — swinging up and dropping down is where knees complain.",
    ],
    "Leg Press": [
        "Sit in the machine with the whole back and hips against the pad.",
        "Place the feet shoulder-width apart in the middle of the platform.",
        "Release the safeties and lower the platform by bending the knees toward the chest.",
        "Stop the moment the low back begins to lift off the pad — that is your depth limit.",
        "Press back up through the whole foot without locking the knees out hard.",
    ],
    "Lying Leg Curls": [
        "Lie face down on the machine with the knee joints level with the pivot.",
        "Set the ankle pad just above the heels and take the handles.",
        "Curl the heels toward the glutes as far as the machine allows.",
        "Keep the hips pressed into the pad — lifting them means the weight is too heavy.",
        "Lower slowly until the legs are almost straight.",
    ],
    "Lying Prone Quadriceps": [
        "Lie face down on a mat with the legs straight and the forehead resting on one forearm.",
        "Bend one knee and reach back with the free hand to hold the ankle or foot.",
        "Draw the heel gently toward the glute until the front of the thigh lengthens.",
        "Keep the hips square and pressed to the floor rather than rolling to one side.",
        "Hold and breathe, then release slowly and change sides.",
    ],
    "Seated Calf Raise": [
        "Sit at the machine with the balls of the feet on the platform and the pads across the lower thighs.",
        "Release the safety and let the heels drop below the platform until the calves lengthen.",
        "Press through the balls of the feet to raise the heels as high as they will go.",
        "Hold the top for a second.",
        "Lower slowly — the bent knee shifts the work to the soleus, the deeper calf muscle.",
    ],
    "Seated Glute": [
        "Sit tall on a chair or bench with both feet flat on the floor.",
        "Cross one ankle over the opposite knee so the shin is roughly parallel to the floor.",
        "Keep the crossed leg's knee relaxed out to the side.",
        "Hinge forward from the hips with a long spine until the glute lengthens.",
        "Hold and breathe, then sit up slowly and change sides.",
    ],
    "Seated Leg Curl": [
        "Sit in the machine with the back against the pad and the knee joints level with the pivot.",
        "Set the thigh pad down firmly and place the ankles over the lower pad.",
        "Curl the heels down and under as far as the machine allows.",
        "Pause at full contraction rather than snapping back.",
        "Return slowly until the legs are almost straight.",
    ],
    "Single Leg Glute Bridge": [
        "Lie on your back with both knees bent and the feet flat on the floor.",
        "Lift one foot and hold that knee toward the chest, or extend the leg straight.",
        "Drive through the heel of the planted foot to raise the hips.",
        "Keep the hips level — the side that drops is the one that needs the work.",
        "Lower under control and complete the reps before changing sides.",
    ],
    "Split Squat": [
        "Take a long step forward into a split stance and hold a dumbbell in each hand.",
        "Set both feet planted — you are moving straight up and down, not stepping.",
        "Lower until the back knee approaches the floor and the front thigh is roughly parallel.",
        "Keep the torso upright and the front shin close to vertical.",
        "Drive through the front heel to stand, and finish the side before changing.",
    ],
    "Standing Calf Raise": [
        "Stand tall with the balls of the feet on the floor or the edge of a step.",
        "Hold a support lightly for balance if you need it.",
        "Press through the balls of the feet to raise the heels as high as they will go.",
        "Hold the top for a full second.",
        "Lower slowly through the full range — calves answer to time under tension, not to bouncing.",
    ],
    "Standing Hip Circles": [
        "Stand tall and hold a support with one hand for balance.",
        "Lift one knee to about hip height in front of you.",
        "Draw slow circles with that knee, opening the hip out to the side and back.",
        "Keep the standing leg soft and the torso upright rather than leaning away.",
        "Reverse the direction, then change sides.",
    ],
    "Sumo Deadlift": [
        "Set the feet well wider than the shoulders with the toes turned out, bar over the mid-foot.",
        "Push the hips down and back and take an overhand grip inside the knees.",
        "Set the chest up, flatten the back and pull the slack out of the bar.",
        "Drive the floor apart with the feet and open the hips as the bar rises.",
        "Finish standing tall, then push the hips back to lower the bar along the same path.",
    ],
})

INSTRUCTIONS.update({

    # ----------------------------------------------------------- shoulders ---
    "Arm Circles": [
        "Stand tall with the feet hip-width apart and the arms extended out to the sides at shoulder height.",
        "Make small forward circles, about the width of a dinner plate, keeping the arms long.",
        "Gradually widen the circles over ten to fifteen seconds.",
        "Reverse the direction and repeat, keeping the shoulders down away from the ears.",
    ],
    "Arnold Dumbbell Press": [
        "Sit on a bench with back support, holding a dumbbell in each hand at chest height, palms facing you.",
        "Press up while rotating the palms outward, so they face forward at the top.",
        "Finish with the arms straight overhead and the ribs down.",
        "Reverse the path exactly, rotating the palms back toward you as you lower.",
        "Use less weight than a straight press — the rotation is what costs you.",
    ],
    "Band Lateral Raise": [
        "Stand on the middle of a resistance band with the feet hip-width apart.",
        "Hold an end in each hand at your sides with the palms facing in.",
        "Lead with the elbows and raise the arms out to the sides to shoulder height.",
        "Stop level with the shoulders rather than going higher.",
        "Lower slowly against the band — with bands the lowering half is the useful half.",
    ],
    "Band Pull Apart": [
        "Hold a resistance band with both hands, arms extended straight in front at chest height.",
        "Set the hands about shoulder-width apart so there is light tension on the band.",
        "Keeping the arms long, pull the hands apart until the band touches the chest.",
        "Squeeze the shoulder blades together and hold for a beat.",
        "Return slowly to the start — this is the best two minutes you can spend before pressing.",
    ],
    "Barbell Shoulder Press": [
        "Set a barbell at shoulder height and take an overhand grip just outside the shoulders.",
        "Unrack it to the front of the shoulders and stand tall with the feet hip-width apart.",
        "Squeeze the glutes and keep the ribs down so the press does not become a standing backbend.",
        "Press the bar overhead, moving the head back slightly to let it pass, then through as it locks out.",
        "Lower under control to the front of the shoulders before the next repetition.",
    ],
    "Bent Over Rear Delt Raise": [
        "Sit on the end of a bench and hinge forward until the chest rests near the thighs.",
        "Hold a dumbbell in each hand hanging beneath the shoulders, palms facing each other.",
        "Think of pulling the dumbbells apart rather than lifting them up.",
        "Raise the arms out to the sides until level with the shoulders, elbows softly bent.",
        "Lower slowly — this is a small muscle, so the weight should be small too.",
    ],
    "Cable Lateral Raise": [
        "Set a pulley at the lowest position and stand side-on with the handle in the far hand.",
        "Let the arm hang across the front of the body with light tension on the cable.",
        "Lead with the elbow and raise the arm out to the side to shoulder height.",
        "Stop level with the shoulder and pause briefly.",
        "Lower slowly, keeping tension at the bottom, then change sides.",
    ],
    "Cable Rear Delt Fly": [
        "Set two pulleys at shoulder height and stand between them.",
        "Take the left handle in the right hand and the right handle in the left, arms crossed in front.",
        "Keep the elbows softly bent and fixed at that angle.",
        "Pull the arms out and back until they are level with the shoulders and wide open.",
        "Return slowly across the body — the cable keeps tension where dumbbells lose it.",
    ],
    "Dumbbell Shoulder Press": [
        "Sit on a bench with back support and hold a dumbbell in each hand at shoulder height.",
        "Turn the palms to face forward with the wrists stacked over the elbows.",
        "Set the ribs down and brace the trunk.",
        "Press both dumbbells overhead until the arms are straight.",
        "Lower under control to shoulder height without letting the low back arch.",
    ],
    "External Rotation": [
        "Stand or sit holding a light dumbbell in one hand with the elbow bent to 90 degrees.",
        "Pin that elbow against your side and keep it there for the whole set.",
        "Rotate the forearm outward, away from the body, as far as is comfortable.",
        "Return slowly to the front — only the forearm moves.",
        "Two to five kilos is the whole useful range here; this is a cuff drill, not a lift.",
    ],
    "Face Pull": [
        "Set a rope on a pulley at roughly face height and take an end in each hand.",
        "Step back until the arms are extended and there is tension, thumbs pointing back.",
        "Pull the rope toward your forehead, driving the elbows high and wide.",
        "Separate the hands as they arrive beside the ears and squeeze the shoulder blades.",
        "Return to full extension under control — this is the movement that keeps pressing pain-free.",
    ],
    "Front Dumbbell Raise": [
        "Stand tall with a dumbbell in each hand resting against the front of the thighs.",
        "Keep the elbows softly bent and the trunk braced.",
        "Raise one arm forward to shoulder height, palm facing down.",
        "Stop level with the shoulder rather than swinging higher.",
        "Lower slowly and alternate arms, resisting the urge to rock the hips.",
    ],
    "Machine Shoulder Press": [
        "Set the seat so the handles sit level with the shoulders when seated.",
        "Sit back with the whole spine against the pad and the feet flat.",
        "Take the handles with the palms facing forward and the wrists stacked over the elbows.",
        "Press overhead until the arms are straight, without shrugging the shoulders up.",
        "Lower under control until the hands are back level with the shoulders.",
    ],
    "Reverse Flyes": [
        "Hinge forward from the hips with a long spine, holding a dumbbell in each hand.",
        "Let the arms hang beneath the shoulders with the thumbs pointing down.",
        "Keep the elbows softly bent and fixed at that angle.",
        "Raise the arms out to the sides until level with the shoulders.",
        "Lower slowly, keeping the torso still rather than rocking up with each rep.",
    ],
    "Side Lateral Raise": [
        "Stand tall with a dumbbell in each hand at your sides, palms facing in.",
        "Keep the elbows softly bent and the trunk braced.",
        "Lead with the elbows and raise both arms out to the sides to shoulder height.",
        "Stop level with the shoulders — higher hands the work to the traps.",
        "Lower slowly. This is a small muscle, so keep the weight light.",
    ],

    # ------------------------------------------------------------- triceps ---
    "Bench Dips": [
        "Sit on the edge of a bench and place the hands beside the hips, fingers forward.",
        "Slide the hips forward off the bench with the legs extended or the knees bent.",
        "Keep the hips close to the bench and lower by bending the elbows straight back.",
        "Stop when the upper arms are roughly parallel to the floor.",
        "Press back to straight arms — drifting away from the bench is what strains the shoulder.",
    ],
    "Close-Grip Bench Press": [
        "Lie on a flat bench and grip the bar just inside shoulder width.",
        "Set the shoulder blades together and down and unrack the bar over the chest.",
        "Lower it to the lower chest, keeping the elbows tucked close to the ribs.",
        "Press back to straight arms, driving through the triceps.",
        "Any narrower than shoulder width and the wrists pay for it.",
    ],
    "Close-Grip Push-Up": [
        "Set up in a push-up position with the hands directly under the shoulders.",
        "Tuck the toes under and hold the body in one straight line from head to heels.",
        "Lower the chest with the elbows tracking back along the ribs, not flaring out.",
        "Stop just short of the floor, then press back to straight arms.",
        "Keeping the elbows close is what moves the work to the triceps.",
    ],
    "Dumbbell Overhead Triceps Extension - Two Hands": [
        "Sit or stand tall and hold one dumbbell vertically in both hands, palms under the top plate.",
        "Press it overhead until the arms are straight, elbows pointing at the ceiling.",
        "Keeping the upper arms still, lower the dumbbell behind the head.",
        "Go until you feel the triceps lengthen, without letting the elbows flare wide.",
        "Press back to straight arms — one dumbbell in both hands is steadier than two.",
    ],
    "EZ-Bar Skullcrusher": [
        "Lie on a flat bench holding an EZ-bar over the chest with a close overhand grip.",
        "Angle the upper arms slightly back toward the head rather than straight up.",
        "Keeping the upper arms still, bend the elbows to lower the bar toward the forehead.",
        "Stop at the forehead or just behind it.",
        "Extend the elbows to press back up, keeping the upper arms in the same place throughout.",
    ],
    "Incline Close-Grip Push-Up": [
        "Place the hands close together on a bench, step or sturdy table.",
        "Walk the feet back until the body is one straight line from head to heels.",
        "Lower the chest toward the hands with the elbows tracking back along the ribs.",
        "Press back to straight arms without letting the hips sag.",
        "The higher the surface, the easier it is — this is the triceps push-up a beginner can do.",
    ],
    "Lying Triceps Press": [
        "Lie on a flat bench holding a barbell over the chest with a close overhand grip.",
        "Angle the upper arms slightly back toward the head and keep them there.",
        "Bend the elbows to lower the bar to the forehead or just behind it.",
        "Keep the upper arms still — only the forearms move.",
        "Extend the elbows to press the bar back to the starting position.",
    ],
    "One-Arm Cable Pushdown": [
        "Set a single handle on a high pulley and stand facing the machine.",
        "Take the handle in one hand and tuck that elbow against your side.",
        "Push the hand down until the arm is straight, keeping the elbow still.",
        "Squeeze the triceps at the bottom for a beat.",
        "Return under control and complete the set before changing sides.",
    ],
    "Standing Dumbbell Triceps Extension": [
        "Stand tall holding a dumbbell in one hand, pressed overhead with a straight arm.",
        "Point the elbow at the ceiling and brace the trunk so the ribs stay down.",
        "Bend the elbow to lower the dumbbell behind the head.",
        "Keep the upper arm still and vertical throughout.",
        "Extend the elbow to press back overhead, then change sides.",
    ],
    "Tricep Dumbbell Kickback": [
        "Place one knee and the same-side hand on a bench, torso parallel to the floor.",
        "Hold a dumbbell in the free hand and raise that upper arm until it is level with the torso.",
        "Keep the upper arm fixed there for the whole set.",
        "Extend the elbow to straighten the arm behind you and squeeze the triceps.",
        "Return to 90 degrees under control — only the forearm moves.",
    ],
    "Triceps Overhead Extension with Rope": [
        "Set a rope on a low pulley and face away from the machine, rope held overhead.",
        "Step forward into a split stance with the elbows pointing ahead and bent behind the head.",
        "Keeping the upper arms still, extend the elbows until the arms are straight overhead.",
        "Pull the ends of the rope apart at the top.",
        "Return slowly behind the head — the overhead position stretches the part pushdowns miss.",
    ],
    "Triceps Pushdown": [
        "Attach a straight bar to a high pulley and stand facing the machine, feet hip-width apart.",
        "Take an overhand grip and tuck the elbows firmly against your sides.",
        "Push the bar down until the arms are straight, keeping the elbows still.",
        "Squeeze the triceps at the bottom for a beat.",
        "Return until the forearms are just above parallel, without letting the elbows travel forward.",
    ],

    # ---------------------------------------------------------------- core ---
    "Ab Wheel Rollout": [
        "Kneel on a mat and hold the wheel handles under the shoulders with straight arms.",
        "Tuck the pelvis so the low back is flat and brace the trunk hard.",
        "Roll the wheel forward only as far as you can hold that flat back.",
        "Pull through the abdominals to draw the wheel back underneath you.",
        "If the low back arches at any point, shorten the range — that distance is your working range.",
    ],
    "Cable Crunch": [
        "Kneel facing a high pulley and hold a rope beside the head with both hands.",
        "Set the hips back so there is tension on the cable before you move.",
        "Curl the spine down, bringing the ribs toward the hips.",
        "Keep the hips still — folding at the hips turns this into a different exercise.",
        "Return slowly, letting the spine extend under the cable's pull.",
    ],
    "Crunches": [
        "Lie on your back with the knees bent and the feet flat on the floor.",
        "Rest the hands lightly beside the head without pulling on the neck.",
        "Curl the ribs toward the hips, lifting the shoulder blades a few centimetres off the floor.",
        "Pause at the top and breathe out.",
        "Lower slowly until the shoulder blades touch down.",
    ],
    "Dead Bug": [
        "Lie on your back with the arms straight above the shoulders and the knees over the hips, bent to 90 degrees.",
        "Press the low back firmly into the floor and hold it there for the whole set.",
        "Slowly lower one arm overhead and the opposite leg toward the floor.",
        "Stop the moment the low back begins to lift — that is your range.",
        "Return to the start and repeat on the other side.",
    ],
    "Dumbbell Side Bend": [
        "Stand tall with one dumbbell in one hand and the other hand resting on the hip.",
        "Keep the feet hip-width apart and the shoulders square to the front.",
        "Bend sideways toward the weighted side, letting the dumbbell travel down the leg.",
        "Return upright by pulling with the opposite side of the trunk.",
        "Hold only one dumbbell — holding two cancels the movement out.",
    ],
    "Exercise Ball Crunch": [
        "Sit on an exercise ball and walk the feet forward until the low back is supported on it.",
        "Set the feet flat and about hip-width apart for a stable base.",
        "Cross the arms over the chest to keep the hands away from the neck.",
        "Curl the ribs toward the hips, lifting the shoulders off the ball.",
        "Lower slowly and let the spine extend over the ball — that extra range is why you use it.",
    ],
    "Exercise Ball Pull-In": [
        "Start in a push-up position with the shins resting on an exercise ball.",
        "Set the hands under the shoulders and brace the trunk so the hips are level.",
        "Draw the knees toward the chest, rolling the ball forward.",
        "Keep the hips from piking up toward the ceiling.",
        "Extend the legs slowly back to the plank position.",
    ],
    "Hanging Leg Raise": [
        "Hang from a bar with an overhand grip and the shoulders pulled down away from the ears.",
        "Tilt the pelvis back and brace before the legs move.",
        "Raise both legs together until the thighs are at least parallel to the floor.",
        "Avoid swinging — if the body starts rocking, lower the range.",
        "Lower the legs slowly to a full hang.",
    ],
    "Leg Raise on Parallel Bars": [
        "Support yourself on parallel bars with the forearms on the pads and the back against the rest.",
        "Let the legs hang straight and set the shoulders down away from the ears.",
        "Tilt the pelvis back, then raise the legs until the thighs are parallel to the floor.",
        "Lift with the abdominals rather than swinging the legs up.",
        "Lower slowly to a full hang before the next repetition.",
    ],
    "Lying Leg Raise": [
        "Lie on your back with the legs straight and the hands tucked under the hips.",
        "Press the low back flat into the floor and hold it there.",
        "Raise both legs together until they are vertical.",
        "Lower them slowly, stopping the moment the low back begins to lift away.",
        "Bend the knees to shorten the lever if you cannot hold the back flat.",
    ],
    "Pallof Press": [
        "Set a handle on a pulley at chest height and stand side-on, a stride away from it.",
        "Hold the handle at the chest with both hands and set the feet shoulder-width apart.",
        "Brace the trunk, then press the hands straight out in front of the chest.",
        "Resist the cable's pull to rotate you — not rotating is the entire exercise.",
        "Return the hands to the chest under control, then change sides.",
    ],
    "Plank": [
        "Lie face down and set the forearms on the floor with the elbows directly under the shoulders.",
        "Tuck the toes and lift the hips until the body is one straight line from head to heels.",
        "Squeeze the glutes and brace the trunk as if about to be punched in the stomach.",
        "Hold, breathing normally, without letting the hips sag or ride up.",
        "Lower the knees to finish rather than collapsing out of the position.",
    ],
    "Russian Twist": [
        "Sit on the floor with the knees bent and lean the torso back to about 45 degrees.",
        "Hold the hands together in front of the chest and keep the chest tall.",
        "Rotate the ribs and shoulders to one side, following the hands with the eyes.",
        "Return through the middle and rotate to the other side.",
        "Rotate the ribs, not just the arms, and keep the heels down if the low back complains.",
    ],
    "Standing Cable Wood Chop": [
        "Set a handle on a high pulley and stand side-on with the feet shoulder-width apart.",
        "Take the handle in both hands above the far shoulder with the arms extended.",
        "Pull down and across the body toward the opposite hip, pivoting the back foot.",
        "Rotate through the hips and mid-back rather than the low back.",
        "Return along the same path under control, then complete the side before changing.",
    ],

    # -------------------------------------------------------------- cardio ---
    "Elliptical Trainer": [
        "Step onto the pedals and hold the moving handles with a light grip, standing tall.",
        "Start pedalling at an easy pace for two to three minutes to warm up.",
        "Raise the resistance until the effort is moderate but you could still speak in short sentences.",
        "Keep the whole foot on the pedal and drive with the legs rather than pulling with the arms.",
        "Lower the resistance for the final two minutes to bring the breathing down.",
    ],
    "Jump Rope": [
        "Hold a handle in each hand with the rope resting on the floor behind your heels.",
        "Set the elbows close to the ribs and turn the rope with the wrists, not the whole arm.",
        "Jump a couple of centimetres off the ground off the balls of the feet as the rope comes round.",
        "Land softly with the knees slightly bent and hold a steady turning pace.",
        "Start with bouts of twenty to thirty seconds and build up as the coordination comes.",
    ],
    "Mountain Climbers": [
        "Start in a push-up position with the hands under the shoulders and the body in one line.",
        "Brace the trunk and draw one knee toward the chest without letting the hips rise.",
        "Switch legs, driving the other knee forward as the first foot returns.",
        "Keep the shoulders stacked over the hands rather than drifting behind them.",
        "Keep alternating at a steady rhythm, breathing continuously, for the prescribed time.",
    ],
    "Rowing Machine": [
        "Sit on the seat, strap the feet in, and take the handle with an overhand grip.",
        "Start compressed at the front with the shins vertical and the arms straight.",
        "Drive with the legs first, then swing the torso back, then pull the arms to the ribs.",
        "Reverse that order coming forward: arms away, torso over, then let the knees bend.",
        "Keep the spine long throughout rather than rounding at either end of the stroke.",
    ],
    "Stair Climbing": [
        "Step onto the machine and start at a slow pace to find your rhythm.",
        "Stand tall with the shoulders back, resting the hands on the rails for balance only.",
        "Take full steps, driving through the whole foot rather than the toes.",
        "Raise the speed until the effort is moderate and you could still speak in short sentences.",
        "Ease the pace back for the final two minutes to bring the heart rate down.",
    ],
    "Stationary Cycling": [
        "Set the saddle so that at the bottom of the pedal stroke the knee is almost straight.",
        "Sit tall with a light grip on the handlebars and the shoulders relaxed.",
        "Pedal easily for two to three minutes before adding resistance.",
        "Raise the resistance until the effort is moderate and sustainable, keeping a smooth cadence.",
        "Ease the resistance off for the last few minutes to cool down.",
    ],

    # ----------------------------------------------------------- full body ---
    "Inchworm": [
        "Stand tall with the feet hip-width apart.",
        "Hinge forward and place the hands on the floor, bending the knees as much as you need to.",
        "Walk the hands forward until you reach a plank position with the body in one line.",
        "Hold for a beat, then walk the hands back toward the feet.",
        "Roll up to standing and repeat, letting the legs straighten a little more each time.",
    ],
    "Wrist Circles": [
        "Extend both arms in front of you at shoulder height and make loose fists.",
        "Circle the hands slowly in one direction, moving only at the wrist.",
        "Keep the forearms still so the movement stays in the joint you are preparing.",
        "Reverse the direction after ten to fifteen seconds.",
    ],
})

# The sixteen movements this project authored for the previous library. Their
# prose was good — these were among the most-prescribed entries in the app — but
# it lived in a 902-row snapshot of the library being replaced. Rewritten here so
# every instruction in the library sits in one file, in one voice.
INSTRUCTIONS.update({

    "Superman Hold": [
        "Lie face down on a mat with the arms extended overhead and the legs straight.",
        "Draw the shoulders down away from the ears and lengthen through the spine.",
        "Lift the arms, chest and legs a few centimetres off the floor at the same time.",
        "Think long rather than high — reach away through the fingers and toes.",
        "Hold, breathing normally, then lower everything together under control.",
    ],
    "Prone Swimmer": [
        "Lie face down with the arms extended overhead and the forehead resting on the mat.",
        "Lift both arms a few centimetres off the floor and keep them there.",
        "Sweep one arm out to the side and down toward the hip, then back overhead.",
        "Move slowly and keep the hips and ribs pressed into the floor.",
        "Alternate arms for the prescribed time — this is upper-back endurance, not a lift.",
    ],
    "Wall Angel Row": [
        "Stand with the back flat against a wall and the feet a few centimetres out from it.",
        "Press the low back, upper back and head into the wall and keep all three in contact.",
        "Set the arms against the wall with the elbows bent to 90 degrees at shoulder height.",
        "Draw the elbows down and back into the wall, squeezing the shoulder blades together.",
        "Return to the start slowly — if the low back lifts away, you have gone too far.",
    ],
    "Self-Resisted Biceps Curl": [
        "Stand tall and place one hand palm-up at waist height, elbow tucked against your side.",
        "Press the other palm down on top of it to create resistance.",
        "Curl the lower hand toward the shoulder while the upper hand pushes back against it.",
        "Push down hard enough that the last two reps are a genuine fight.",
        "Lower slowly under the same resistance, then change sides.",
    ],
    "Kettlebell Swing": [
        "Stand with the feet slightly wider than the hips and a kettlebell on the floor an arm's length ahead.",
        "Hinge at the hips with a long spine, tip the bell toward you and hike it back between the legs.",
        "Snap the hips forward to stand tall, letting the bell float up to about chest height.",
        "Keep the arms relaxed — they are rope, the hips throw the bell.",
        "Let it swing back between the legs as the hips hinge again, and keep the spine long throughout.",
    ],
    "Bird Dog": [
        "Start on hands and knees with the wrists under the shoulders and the knees under the hips.",
        "Brace the trunk so the low back is flat and the hips are square to the floor.",
        "Extend one arm forward and the opposite leg back until both are level with the torso.",
        "Reach long rather than high, and do not let the hips rotate.",
        "Return under control and repeat on the other side.",
    ],
    "Brisk Walking": [
        "Set off at a pace that feels purposeful rather than casual.",
        "Stand tall with the shoulders relaxed and let the arms swing naturally.",
        "Aim for an effort where talking takes a little work but is still possible.",
        "Take the first and last two minutes easier to warm up and cool down.",
        "Keep the pace steady rather than surging and slowing.",
    ],
    "High Knees": [
        "Stand tall with the feet hip-width apart and the arms bent at your sides.",
        "Drive one knee up toward hip height while pushing off the opposite foot.",
        "Land softly on the ball of the foot and immediately drive the other knee up.",
        "Stay light and quick, keeping the chest up rather than leaning back.",
        "Continue alternating at a steady rhythm for the prescribed time.",
    ],
    "Jumping Jacks": [
        "Stand tall with the feet together and the arms at your sides.",
        "Jump the feet out wider than the hips while sweeping the arms overhead.",
        "Land softly through the whole foot with the knees slightly bent.",
        "Jump the feet back together and bring the arms down.",
        "Keep a steady rhythm and stay relaxed through the shoulders.",
    ],
    "Burpees": [
        "Stand tall, then squat down and place both hands on the floor in front of the feet.",
        "Jump or step the feet back into a plank with the body in one straight line.",
        "Jump or step the feet back in toward the hands.",
        "Stand or jump up to finish the repetition.",
        "Pace it from the first rep — burpees punish anyone who starts at a sprint.",
    ],
    "Child's Pose": [
        "Kneel on a mat and bring the big toes together, letting the knees fall wide.",
        "Sit the hips back toward the heels and walk the hands forward along the floor.",
        "Rest the forehead down and let the arms stay long and relaxed.",
        "Breathe into the back of the ribs and let the shoulders soften with each exhale.",
        "Walk the hands back in and sit up slowly to come out.",
    ],
    "T-Bar Row": [
        "Stand over the bar with the feet either side and take the handle with both hands.",
        "Hinge forward from the hips to about 45 degrees, keeping the spine long and the knees soft.",
        "Let the weight hang at arm's length beneath the chest.",
        "Row the handle to the lower ribs by driving the elbows back.",
        "Lower under control to straight arms, holding the back angle steady throughout.",
    ],
    "Air Bike": [
        "Sit on the bike, set the seat so the knee is almost straight at the bottom of the stroke.",
        "Take the handles and start turning the pedals easily for a minute to warm up.",
        "Drive with the legs and pull and push with the arms together.",
        "Work at the effort the interval calls for — the resistance rises with how hard you go.",
        "Ease back to an easy spin between intervals rather than stopping dead.",
    ],
    "Battle Ropes": [
        "Take an end of the rope in each hand and stand facing the anchor, feet shoulder-width apart.",
        "Sit into a quarter squat with the chest up and the trunk braced.",
        "Drive one arm down as the other comes up, sending alternating waves along the rope.",
        "Keep the hips low and let the arms work independently.",
        "Maintain the wave for the prescribed time rather than chasing height.",
    ],
    "Sprint Intervals (HIIT)": [
        "Warm up with three to five minutes of easy jogging or cycling.",
        "Accelerate to near-maximal effort and hold it for twenty to thirty seconds.",
        "Ease right down to a walk or slow jog for the recovery period.",
        "Repeat the cycle for the prescribed number of rounds.",
        "Finish with three minutes easy — maximal effort by definition, so if you can talk, it is not this.",
    ],
    "HIIT Circuit": [
        "Choose four movements you can perform safely without close attention to form.",
        "Work at a hard but controlled effort on the first for the prescribed interval.",
        "Move to the next with a short rest between, keeping the transitions brisk.",
        "Complete all four to finish one round, then rest fully before the next.",
        "The rest is part of the prescription — cutting it short makes this easier, not harder.",
    ],
})
