"""Generate the clinical review packet for the gym exercise knowledge base.

18 of the 902 exercises carry `contraindications_reviewed`. The other 884 have
rule-derived safety tags that nobody clinically qualified has looked at, and
inspecting a handful of them has already turned up three systematic faults:
every barbell exercise marked unsuitable for Pitta, maximal-effort conditioning
carrying no cardiovascular tag while a dance class did, and thirteen
foam-rolling entries filed as strength training.

Reviewing 884 rows one at a time is a data-entry job nobody will finish. But the
tags were generated by RULES, so their errors are systematic rather than random —
which means the reviewable unit is the rule, not the row. This groups the library
by the mechanism a clinician actually reasons about (what the movement does, and
to what) and reports how consistently each contraindication is applied across it.

A group tagged 70/70 is a rule that fired everywhere; a group tagged 3/13 is a
rule that half-fired, and one of those two answers is wrong. Partial coverage is
where the errors live, so the packet sorts by it.

Run: python scripts/build_gym_review_packet.py
"""
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from services.gym_plan_engine import (  # noqa: E402
    _LIFT_PATTERNS, _is_impact, _lift_class, _movement_pattern, _muscle_key,
    gym_exercises,
)


def _named_lift_class(ex):
    """The lift the NAME identifies, with no muscle-group fallback.

    `_lift_class` falls back to the muscle so that every weighted movement can be
    priced. That is right for load and wrong for review: it swept 129 unnamed leg
    movements into one `leg_extension` bucket, and a coverage figure over a bucket
    like that says nothing about any rule.
    """
    for lift, rx in _LIFT_PATTERNS:
        if rx.search(ex.get("name", "")):
            return lift
    return None

OUT = Path(__file__).resolve().parent.parent / "data" / "golden"
# Below this a group is too small for its coverage to mean anything.
MIN_GROUP = 4
# Coverage inside this band is a rule that fired on some of a group and not the
# rest — the shape of every tagging fault found so far. Outside it the rule at
# least applied itself consistently, which is a different (and cheaper) question.
PARTIAL_LOW, PARTIAL_HIGH = 0.15, 0.85


def _groups():
    """The library, grouped by the mechanism a clinician reasons about."""
    groups = defaultdict(list)
    for ex in gym_exercises:
        lift = _named_lift_class(ex)
        # Movements the name does not identify are grouped by what they DO
        # instead, which is the next-best mechanism description available.
        key = lift or f"({_movement_pattern(ex)})"
        groups[(key, _muscle_key(ex))].append(ex)
    return groups


def _coverage_rows():
    rows = []
    for (lift, muscle), members in sorted(_groups().items()):
        if len(members) < MIN_GROUP:
            continue
        tags = {t for ex in members for t in ex["contraindications"]}
        for tag in sorted(tags):
            carrying = [ex for ex in members if tag in ex["contraindications"]]
            share = len(carrying) / len(members)
            rows.append({
                "movement_class": lift,
                "muscle_group": muscle,
                "contraindication": tag,
                "tagged": len(carrying),
                "group_size": len(members),
                "coverage": f"{share:.0%}",
                "inconsistent": "REVIEW" if PARTIAL_LOW < share < PARTIAL_HIGH else "",
                "examples_tagged": " | ".join(e["name"] for e in carrying[:3]),
                "examples_untagged": " | ".join(
                    e["name"] for e in members if tag not in e["contraindications"])[:120],
                "tag_correct_for_this_movement__Y_N": "",
                "coverage_correct__Y_N": "",
                "missing_contraindications": "",
                "reviewer_notes": "",
            })
    # Biggest genuinely-ambiguous rules first: those are where a wrong answer
    # reaches the most practitioners.
    rows.sort(key=lambda r: (r["inconsistent"] != "REVIEW", -int(r["group_size"])))
    return rows


def _exercise_rows():
    return [{
        "id": ex["id"],
        "name": ex["name"],
        "category": ex["category"],
        "equipment": ex["equipment"],
        "level": ex["level"],
        "movement_pattern": _movement_pattern(ex),
        "movement_class": _lift_class(ex) or "",
        "muscle_group": _muscle_key(ex),
        "is_impact": "yes" if _is_impact(ex) else "",
        "contraindications": ", ".join(ex["contraindications"]),
        # Which of them a person wrote, and which a mechanism rule produced. The
        # reviewer should not have to treat both as equally settled.
        # The reasoning, so the reviewer confirms a stated mechanism rather than
        # reverse-engineering intent from a list of tags.
        "why": ex.get("clinical_rationale", ""),
        "basis": ex.get("clinical_basis", ""),
        "what_a_rule_would_have_said": ", ".join(ex.get("contraindications_derived") or []),
        "role": ex.get("role", ""),
        "skill_floor": ex.get("skill_floor", ""),
        "pregnancy_safe": ex["pregnancy_safe"],
        "dosha_vata": ex["dosha_suitability"]["vata"],
        "dosha_pitta": ex["dosha_suitability"]["pitta"],
        "dosha_kapha": ex["dosha_suitability"]["kapha"],
        "already_reviewed": "yes" if ex.get("contraindications_reviewed") else "",
        "safety_ok__Y_N": "",
        "pregnancy_ok__Y_N": "",
        "corrections": "",
    } for ex in sorted(gym_exercises, key=lambda e: (_lift_class(e) or "zz", e["name"]))]


def _risk_mechanism_rows():
    """One row per mechanism group — the unit a reviewer rules on.

    `risk_tags` are authored by mechanism in `gym_library/mechanisms.py`, each
    group with its reason stated once, so the review is a confirmation of the
    group rather than 70 separate rows."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from gym_library.mechanisms import MECHANISMS
    from engine.movement_risk import _CONDITION_RISK_TAGS, _INJURY_RISK_TAGS

    rows = []
    for tag, group in sorted(MECHANISMS.items()):
        rows.append({
            "mechanism": tag,
            "why": group["why"],
            "movements": "; ".join(sorted(group["movements"])),
            "conditions_that_withhold_it": ", ".join(sorted(
                k for k, v in _CONDITION_RISK_TAGS.items() if tag in v)),
            "injuries_that_withhold_it": ", ".join(sorted(
                k for k, v in _INJURY_RISK_TAGS.items() if tag in v)),
            "movements_missing__list": "",
            "movements_wrongly_included__list": "",
            "vaidya_ruling": "",
        })
    return rows


def _adaptation_rows():
    """The rules that change a plan after it is written, with their live values.

    Read from the modules that apply them, so the packet cannot describe a
    threshold the code no longer uses. Each is a coaching default chosen in
    engineering, and none has been reviewed by anyone qualified to choose it."""
    from services import gym_plan_engine as eng
    from services import gym_week_adjust as wk
    from services import workout_log as wl

    def row(rule, value, applies, exceptions, basis, question):
        return {"rule": rule, "current_value": value, "applies_to": applies,
                "exceptions": exceptions, "basis": basis,
                "question_for_reviewer": question, "reviewer_ruling": "", "corrections": ""}

    rir = ", ".join(f"{k}={v}" for k, v in wl.EFFORT_RIR.items())
    return [
        row("Effort as reps in reserve", rir, "every logged set",
            "", "RIR-based autoregulation (Helms et al., 2016)",
            "Is 'very hard' = 0 reps in reserve the right reading for someone under an intensity ceiling?"),
        row("Weekly load step up", "+1 kg below 20 kg, +2.5 kg above, or the next kettlebell",
            "an exercise whose logged sets all reached the top of the range, or were rated easy",
            "never in a deload week; never when the check-in says too hard or unwell",
            "double progression", "Are these steps safe for the over-60 and adolescent groups?"),
        row("Weekly load step down", f"x{wk._STEP_DOWN} (about {round((1 - wk._STEP_DOWN) * 100)}% lighter)",
            "an exercise whose sets fell below the range AND were rated very hard", "",
            "coaching default", "Should a failed set ever prompt a larger reduction or a different exercise?"),
        row("Check-in can hold, never raise", "too_hard / unwell -> no rise",
            "every user", "", "asymmetric by design: lowering on a feeling is safe, raising is not",
            "Is holding enough after an illness week, or should loads come down?"),
        row("Warning signs stop the load advice", "; ".join(wk.RED_FLAGS.values()),
            "every user", "", "ACSM's Guidelines 11th ed., signs to terminate exercise",
            "Is the list complete? Should any of these also trigger an urgent-care message?"),
        row("Block counts as progressed", f">= {int(wl._ADHERENCE_TO_PROGRESS * 100)}% of planned sessions logged",
            "every user", "", "coaching default",
            "Is half the block enough evidence to progress?"),
        row("Block counts as finished", f"{wl._BLOCK_DAYS} days after it was written, or any week-3 log",
            "every user", "", "engineering default", ""),
        row("Next block's extra volume", f"+{eng._BLOCK_EXTRA_PRIMARY_SETS} set on main lifts, once (going into block 2)",
            "a progressed block", "pregnancy (maintained, not progressed — ACOG 804)",
            "coaching default", "Should the over-60, cardiac or hypertensive groups get the extra set?"),
        row("Beginner -> intermediate offer", f"{wl.LEVEL_UP_AFTER_BLOCKS} finished, progressed blocks in a row + a measured gain",
            f"adults ({wl._ADULT_FROM}+)", "pregnancy; under 18",
            "novice linear progression runs ~12 weeks (Rippetoe & Baker, Practical Programming)",
            "Is twelve weeks right for people with a chronic condition?"),
        row("Intermediate -> advanced offer", f"{wl._ADVANCED_AFTER_BLOCKS} finished blocks at intermediate + a measured gain",
            f"adults {wl._ADULT_FROM}-{wl._SENIOR_FROM - 1}", f"pregnancy; under 18; {wl._SENIOR_FROM}+ (the engine never prescribes advanced movements there)",
            "product decision (2026-10-06)",
            "Is two months at intermediate enough? Should any condition exclude advanced programming?"),
        row("End-of-block notification", f"once, {wl._BLOCK_LENGTH_DAYS}-{wl._BLOCK_LENGTH_DAYS + wl._NOTIFY_WINDOW_DAYS} days after the plan",
            "the latest gym plan only", "", "engineering default", ""),
        row("Loads from the log", f"strongest set in the last {wl.RECENT_DAYS} days, Epley with effort as RIR",
            "every logged exercise", "sets of more than 15 reps are not used to estimate a max", "Epley (1985)",
            ""),
    ]


def _write_csv(path, rows):
    # lineterminator="\n": csv defaults to CRLF, but .gitattributes normalises the
    # repo to LF, so the default made every regeneration a diff of every row.
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]), lineterminator="\n")
        w.writeheader()
        w.writerows(rows)
    print(f"  wrote {path.name} ({len(rows)} rows)")


def main():
    coverage = _coverage_rows()
    exercises = _exercise_rows()
    _write_csv(OUT / "gym_mechanism_review.csv", coverage)
    _write_csv(OUT / "gym_exercise_review.csv", exercises)
    _write_csv(OUT / "gym_risk_mechanism_review.csv", _risk_mechanism_rows())
    _write_csv(OUT / "gym_adaptation_rules_review.csv", _adaptation_rows())
    from services.gym_condition_guidance import CONDITION_GUIDANCE
    _write_csv(OUT / "gym_condition_guidance_review.csv", [{
        "key": g["key"], "label": g["label"], "matches": ", ".join(g["match"]),
        "note_shown_to_the_practitioner": g["note"], "source": g["source"],
        "vaidya_ruling": "", "corrections": "",
    } for g in CONDITION_GUIDANCE])

    flagged = [r for r in coverage if r["inconsistent"]]
    reviewed = sum(1 for e in gym_exercises if e.get("contraindications_reviewed"))
    summary = {
        "exercises": len(gym_exercises),
        "clinically_reviewed": reviewed,
        "unreviewed": len(gym_exercises) - reviewed,
        "mechanism_groups": len({(r["movement_class"], r["muscle_group"]) for r in coverage}),
        "tag_rules": len(coverage),
        "tag_rules_applied_inconsistently": len(flagged),
        "risk_mechanism_groups": len(_risk_mechanism_rows()),
        "movements_with_a_risk_mechanism": sum(1 for e in gym_exercises if e.get("risk_tags")),
    }
    (OUT / "gym_review_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    print("  wrote gym_review_summary.json")
    for k, v in summary.items():
        print(f"    {k}: {v}")
    print("\n  worst inconsistencies:")
    for r in flagged[:10]:
        print(f"    {r['movement_class']:>18s}/{r['muscle_group']:<10s} "
              f"{r['contraindication']:<20s} {r['tagged']:>3}/{r['group_size']:<3} "
              f"({r['coverage']})")


if __name__ == "__main__":
    main()
