"""Generate the clinical review packet for the gym exercise knowledge base.

18 of the 902 exercises carry `contraindications_reviewed`. The other 884 have
rule-derived safety tags that nobody clinically qualified has looked at, and
inspecting a handful of them has already turned up three systematic faults:
every barbell exercise marked unsuitable for Pitta, maximal-effort conditioning
carrying no cardiovascular tag while a dance class did, and thirteen
foam-rolling entries filed as strength training.

Reviewing 884 rows one at a time is a data-entry job nobody will finish. But the
tags were generated by RULES, so their errors are systematic rather than random —
which means the reviewable unit is the rule, not the row. This groups the library
by the mechanism a clinician actually reasons about (what the movement does, and
to what) and reports how consistently each contraindication is applied across it.

A group tagged 70/70 is a rule that fired everywhere; a group tagged 3/13 is a
rule that half-fired, and one of those two answers is wrong. Partial coverage is
where the errors live, so the packet sorts by it.

Run: python scripts/build_gym_review_packet.py
"""
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from services.gym_plan_engine import (  # noqa: E402
    _LIFT_PATTERNS, _is_impact, _lift_class, _movement_pattern, _muscle_key,
    gym_exercises,
)


def _named_lift_class(ex):
    """The lift the NAME identifies, with no muscle-group fallback.

    `_lift_class` falls back to the muscle so that every weighted movement can be
    priced. That is right for load and wrong for review: it swept 129 unnamed leg
    movements into one `leg_extension` bucket, and a coverage figure over a bucket
    like that says nothing about any rule.
    """
    for lift, rx in _LIFT_PATTERNS:
        if rx.search(ex.get("name", "")):
            return lift
    return None

OUT = Path(__file__).resolve().parent.parent / "data" / "golden"
# Below this a group is too small for its coverage to mean anything.
MIN_GROUP = 4
# Coverage inside this band is a rule that fired on some of a group and not the
# rest — the shape of every tagging fault found so far. Outside it the rule at
# least applied itself consistently, which is a different (and cheaper) question.
PARTIAL_LOW, PARTIAL_HIGH = 0.15, 0.85


def _groups():
    """The library, grouped by the mechanism a clinician reasons about."""
    groups = defaultdict(list)
    for ex in gym_exercises:
        lift = _named_lift_class(ex)
        # Movements the name does not identify are grouped by what they DO
        # instead, which is the next-best mechanism description available.
        key = lift or f"({_movement_pattern(ex)})"
        groups[(key, _muscle_key(ex))].append(ex)
    return groups


def _coverage_rows():
    rows = []
    for (lift, muscle), members in sorted(_groups().items()):
        if len(members) < MIN_GROUP:
            continue
        tags = {t for ex in members for t in ex["contraindications"]}
        for tag in sorted(tags):
            carrying = [ex for ex in members if tag in ex["contraindications"]]
            share = len(carrying) / len(members)
            rows.append({
                "movement_class": lift,
                "muscle_group": muscle,
                "contraindication": tag,
                "tagged": len(carrying),
                "group_size": len(members),
                "coverage": f"{share:.0%}",
                "inconsistent": "REVIEW" if PARTIAL_LOW < share < PARTIAL_HIGH else "",
                "examples_tagged": " | ".join(e["name"] for e in carrying[:3]),
                "examples_untagged": " | ".join(
                    e["name"] for e in members if tag not in e["contraindications"])[:120],
                "tag_correct_for_this_movement__Y_N": "",
                "coverage_correct__Y_N": "",
                "missing_contraindications": "",
                "reviewer_notes": "",
            })
    # Biggest genuinely-ambiguous rules first: those are where a wrong answer
    # reaches the most practitioners.
    rows.sort(key=lambda r: (r["inconsistent"] != "REVIEW", -int(r["group_size"])))
    return rows


def _exercise_rows():
    return [{
        "id": ex["id"],
        "name": ex["name"],
        "category": ex["category"],
        "equipment": ex["equipment"],
        "level": ex["level"],
        "movement_pattern": _movement_pattern(ex),
        "movement_class": _lift_class(ex) or "",
        "muscle_group": _muscle_key(ex),
        "is_impact": "yes" if _is_impact(ex) else "",
        "contraindications": ", ".join(ex["contraindications"]),
        # Which of them a person wrote, and which a mechanism rule produced. The
        # reviewer should not have to treat both as equally settled.
        "contraindications_authored": ", ".join(ex.get("contraindications_authored") or []),
        "role": ex.get("role", ""),
        "skill_floor": ex.get("skill_floor", ""),
        "pregnancy_safe": ex["pregnancy_safe"],
        "dosha_vata": ex["dosha_suitability"]["vata"],
        "dosha_pitta": ex["dosha_suitability"]["pitta"],
        "dosha_kapha": ex["dosha_suitability"]["kapha"],
        "already_reviewed": "yes" if ex.get("contraindications_reviewed") else "",
        "safety_ok__Y_N": "",
        "pregnancy_ok__Y_N": "",
        "corrections": "",
    } for ex in sorted(gym_exercises, key=lambda e: (_lift_class(e) or "zz", e["name"]))]


def _write_csv(path, rows):
    # lineterminator="\n": csv defaults to CRLF, but .gitattributes normalises the
    # repo to LF, so the default made every regeneration a diff of every row.
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]), lineterminator="\n")
        w.writeheader()
        w.writerows(rows)
    print(f"  wrote {path.name} ({len(rows)} rows)")


def main():
    coverage = _coverage_rows()
    exercises = _exercise_rows()
    _write_csv(OUT / "gym_mechanism_review.csv", coverage)
    _write_csv(OUT / "gym_exercise_review.csv", exercises)

    flagged = [r for r in coverage if r["inconsistent"]]
    reviewed = sum(1 for e in gym_exercises if e.get("contraindications_reviewed"))
    summary = {
        "exercises": len(gym_exercises),
        "clinically_reviewed": reviewed,
        "unreviewed": len(gym_exercises) - reviewed,
        "mechanism_groups": len({(r["movement_class"], r["muscle_group"]) for r in coverage}),
        "tag_rules": len(coverage),
        "tag_rules_applied_inconsistently": len(flagged),
    }
    (OUT / "gym_review_summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    print("  wrote gym_review_summary.json")
    for k, v in summary.items():
        print(f"    {k}: {v}")
    print("\n  worst inconsistencies:")
    for r in flagged[:10]:
        print(f"    {r['movement_class']:>18s}/{r['muscle_group']:<10s} "
              f"{r['contraindication']:<20s} {r['tagged']:>3}/{r['group_size']:<3} "
              f"({r['coverage']})")


if __name__ == "__main__":
    main()
