#!/usr/bin/env python3
"""Build `diet_foods.json` from the authored food library.

    python scripts/build_diet_library.py            # status and coverage
    python scripts/build_diet_library.py --check    # fail if the library and the KB disagree
    python scripts/build_diet_library.py --write    # emit the KB (refused until complete)

The library this replaces is generated by `scripts/seed_diet_foods.py`, which produces
the whole Ayurvedic layer of the 150 rows from a ten-row table of category defaults,
roughly six hand-listed name overrides per axis, and substring matches on the food's
id. Every vegetable inherits one rasa profile; every fruit inherits another. This
builder goes the other way: judgment lives in the spec, the definitional maps in
`schema.to_kb_row` do the translation, and nothing is inferred from a name.

## Why --write refuses a partial library

A half-migrated file is worse than either end of the migration. `diet_plan_engine`
composes meals from whatever ids it finds, and `build_vectors` seeds the same file as
300 of the 407 documents in the `nutrition` collection — so writing a 10-food library
over a 150-food one would silently delete 140 foods from both the fallback engine and
the corpus, and the corpus failure is invisible because RAG returning less is not an
error. The gate below is the reason that cannot happen by accident.
"""
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from diet_library import schema  # noqa: E402
from diet_library.spices import SPICES  # noqa: E402

BASE = Path(__file__).resolve().parent.parent
OUT = BASE / "data" / "knowledge_base" / "diet_foods.json"

# Every authored tranche, in the order they will be written. One module per category,
# so a reviewer works through a category at a time and a diff stays readable.
TRANCHES: list[tuple[str, list]] = [
    ("spice", SPICES),
]


def library() -> list[dict]:
    """Every authored food, validated, in the shape the knowledge base holds."""
    seen: dict[str, str] = {}
    rows = []
    for tranche, foods in TRANCHES:
        for food in foods:
            schema.validate(food)          # spec.F validates on construction; again here
            fid = food["id"]               # so an edited dict cannot slip past
            if fid in seen:
                raise schema.SpecError(f"duplicate id {fid!r} in {tranche} and {seen[fid]}")
            seen[fid] = tranche
            rows.append(schema.to_kb_row(food))
    return rows


def current_kb() -> list[dict]:
    if not OUT.exists():
        return []
    return json.loads(OUT.read_text(encoding="utf-8"))


def coverage() -> tuple[set[str], set[str], set[str]]:
    """(authored, still derived, authored-but-not-in-the-current-KB)."""
    authored = {f["id"] for f in library()}
    existing = {f["id"] for f in current_kb()}
    return authored & existing, existing - authored, authored - existing


def report() -> int:
    done, todo, extra = coverage()
    total = len(done) + len(todo)
    pct = (len(done) / total * 100) if total else 0.0
    print(f"authored : {len(done)}/{total}  ({pct:.0f}%)")
    for tranche, foods in TRANCHES:
        print(f"  {tranche:<12} {len(foods):>3}")
    if extra:
        print(f"\nauthored but absent from the current KB ({len(extra)}): {sorted(extra)}")
        print("  — new rows are fine (preparation states split one id into two);")
        print("    a typo in an id looks identical here, so read the list.")
    if todo:
        print(f"\nstill derived ({len(todo)}), first 12: {sorted(todo)[:12]}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the written KB does not match the library")
    ap.add_argument("--write", action="store_true",
                    help="write the KB (refused while any food is still derived)")
    args = ap.parse_args()

    rows = library()

    if args.check:
        done, todo, _ = coverage()
        if todo:
            print(f"library is incomplete — {len(todo)} foods still come from "
                  f"seed_diet_foods.py. Nothing to check yet.")
            return 0
        if current_kb() != rows:
            print("diet_foods.json is out of date — run --write", file=sys.stderr)
            return 1
        print(f"diet_foods.json matches the library ({len(rows)} foods)")
        return 0

    if args.write:
        _, todo, _ = coverage()
        if todo:
            print(
                f"REFUSING to write: {len(todo)} of "
                f"{len(todo) + len(rows)} foods are still derived.\n"
                "Writing now would drop them from `diet_plan_engine` and from the RAG\n"
                "nutrition collection, where this file is 300 of 407 documents — and a\n"
                "corpus that returns less is not an error, so nothing would go red.\n"
                "Author the remaining tranches first.",
                file=sys.stderr)
            return 1
        OUT.write_text(json.dumps(rows, indent=2, ensure_ascii=False) + "\n",
                       encoding="utf-8")
        print(f"wrote {OUT.relative_to(BASE)} ({len(rows)} foods)")
        return 0

    return report()


if __name__ == "__main__":
    sys.exit(main())
