"""The authored food library's vocabulary, and the rules it enforces on its authors.

`diet_foods.json` was generated by `scripts/seed_diet_foods.py` from a ten-row table
of category defaults plus substring matches on the food's id. Measured over its 150
rows: six distinct rasa combinations, `season_suitable` equal to `["all"]` on every
one, `best_for` empty on 140, nutrition a per-category placeholder on 109, no `guna`
field at all, and zero foods with sour Vipaka — a value the generator could not emit.

All 150 rows are authored now and that generator is retired. This file is what holds
the knowledge base and the spec together: it enforces the vocabulary on new rows, and
it asserts that none of the four measurements above can come back.
"""
import sys
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parent.parent / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

from diet_library import schema                     # noqa: E402
from diet_library.spec import F, N                  # noqa: E402
from diet_library.spices import SPICES              # noqa: E402
import build_diet_library as builder                # noqa: E402


def _ok(**over):
    """A minimal admissible row; each test breaks exactly one thing."""
    base = dict(
        category="spice", prep_state="prepared",
        rasa=("katu",), guna=("laghu", "ruksha"), virya="ushna", vipaka="katu",
        dosha=(1, 1, -1), ritu=schema.ALL_RITU,
        nutrition=N(100, 1, 10, 1, 1, source="usda"),
        ref="bhavaprakasha", varga="Haritakyadi",
    )
    base.update(over)
    return F("Test Dravya", **base)


# ── The vocabulary ────────────────────────────────────────────────────────────

def test_vipaka_has_all_three_classical_values():
    """The generator can only write madhura or katu, so Amla Vipaka does not occur
    anywhere in the current 150 rows and every sour food is mislabelled."""
    assert set(schema.VIPAKA) == {"madhura", "amla", "katu"}


def test_guna_is_a_field_at_all():
    """`diet_llm_generator`'s system prompt requires every meal to cite Rasa, Guna,
    Virya and Vipaka. Guna appears on none of the 150 foods, so the model invents
    that axis on every meal of every plan."""
    assert schema.GUNA
    assert all(a in schema.GUNA and b in schema.GUNA for a, b in schema.GUNA_PAIRS)


def test_a_food_cannot_hold_both_halves_of_an_opposed_pair():
    with pytest.raises(schema.SpecError, match="opposed pair"):
        _ok(guna=("guru", "laghu"))


def test_ritu_must_be_stated_and_all_is_a_decision():
    """`season_suitable: ["all"]` on 150 of 150 rows is what a field looks like when
    nobody ever decided. ALL_RITU means it; an empty tuple is refused."""
    with pytest.raises(schema.SpecError, match="at least one ritu"):
        _ok(ritu=())
    assert len(_ok(ritu=schema.ALL_RITU)["ritu"]) == 6


def test_nutrition_needs_a_source():
    """109 of 150 rows carry a per-category constant with nothing recording that they
    do, which is why 27 vegetables report identical macros and nobody noticed."""
    with pytest.raises(schema.SpecError, match="nutrition needs a source"):
        _ok(nutrition={"calories": 1, "protein_g": 1, "carbs_g": 1,
                       "fat_g": 1, "fiber_g": 1, "source": "vibes"})


def test_a_row_must_cite_a_nighantu_and_a_varga():
    with pytest.raises(schema.SpecError, match="varga"):
        _ok(varga="  ")


def test_nothing_may_claim_to_be_reviewed():
    food = _ok()
    food["reviewed"] = True
    with pytest.raises(schema.SpecError, match="reviewed must be False"):
        schema.validate(food)


# ── Contradict only out loud ──────────────────────────────────────────────────

def test_vipaka_must_follow_rasa_unless_a_prabhava_says_otherwise():
    """Charaka Sutrasthana 26: madhura and lavana yield madhura vipaka, amla yields
    amla, katu/tikta/kashaya yield katu."""
    with pytest.raises(schema.SpecError, match="does not follow rasa"):
        _ok(rasa=("katu",), vipaka="madhura")

    licensed = _ok(rasa=("katu",), vipaka="madhura",
                   prabhava="Madhura vipaka despite katu rasa — the Shunthi exception.")
    assert licensed["vipaka"] == "madhura"


def test_dosha_effect_must_follow_rasa_or_virya_unless_a_prabhava_says_otherwise():
    """A rule engine may not decide that a sweet food reduces Kapha. Barley does, and
    honey does, and the texts say so under Prabhava — so the rule is not "never
    contradict", it is "contradict only out loud".

    Yava is the case: madhura rasa raises Kapha, shita virya raises Kapha, and Yava
    reduces it anyway. Both rungs of the hierarchy disagree with the claim, which is
    exactly when a reviewer needs a sentence to argue with.
    """
    # vipaka moves with the rasa so that only the dosha rule is under test.
    with pytest.raises(schema.SpecError, match="runs against rasa"):
        _ok(rasa=("madhura",), vipaka="madhura", virya="shita", dosha=(-1, -1, -1))

    licensed = _ok(rasa=("madhura",), vipaka="madhura", virya="shita", dosha=(-1, -1, -1),
                   prabhava="Yava is kapha-hara despite madhura rasa (BPN Dhanya Varga).")
    assert licensed["dosha_effect"]["kapha"] == -1


def test_virya_licenses_what_rasa_alone_would_forbid():
    """Rasa, then Virya, then Vipaka, then Prabhava — Ashtanga Hridaya Sutrasthana 9.

    The rule read rasa alone at first and demanded a prabhava from every ushna-virya
    food that reduced Vata: Jiraka, Maricha, Yavani, Methika. Those rows are not
    exceptions to the classical system, they are the system one rung up, and a rule
    that fires on ordinary rows teaches authors to satisfy it with a sentence rather
    than a reason.
    """
    # katu rasa raises Vata; ushna virya lowers it. No prabhava needed.
    assert _ok(rasa=("katu",), virya="ushna", dosha=(-1, 1, -1))
    # madhura rasa lowers Pitta; ushna virya raises it. No prabhava needed.
    assert _ok(rasa=("madhura",), vipaka="madhura", virya="ushna", dosha=(-1, 1, 1))
    # Both rungs say Kapha rises. Claiming it falls needs the sentence.
    with pytest.raises(schema.SpecError, match="runs against rasa"):
        _ok(rasa=("madhura",), vipaka="madhura", virya="shita", dosha=(0, 0, -1))


def test_the_rule_caught_four_rows_in_the_first_tranche():
    """Not hypothetical. Jiraka, Maricha, Methika and Yavani were all authored with a
    Vata-reducing effect against a katu or katu-tikta rasa, and each was refused until
    its classical reason was written down."""
    by_id = {f["id"]: f for f in SPICES}
    for fid in ("cumin_jeera", "black_pepper", "fenugreek_seeds_methi", "ajwain"):
        assert by_id[fid]["prabhava"], f"{fid} lost the reason that admits it"


# ── Translation, not judgement ────────────────────────────────────────────────

def test_the_kb_row_speaks_the_vocabulary_the_engine_reads():
    """`diet_plan_engine._SEASON_RASAS` and `_SEASON_VIRYA` are written in English,
    and `build_vectors` prints the same words into the corpus. The spec is Sanskrit;
    the emitted row is both."""
    row = schema.to_kb_row(_ok(rasa=("madhura",), guna=("guru",), virya="shita",
                               vipaka="madhura", dosha=(-1, -1, 1)))
    assert row["ayurvedic"]["rasa"] == ["sweet"]
    assert row["ayurvedic"]["rasa_sanskrit"] == ["madhura"]
    assert row["ayurvedic"]["virya"] == "cooling"
    assert row["ayurvedic"]["vipaka"] == "sweet"


def test_agni_effect_is_derived_from_guna_not_authored():
    """It is the guru/laghu guna restated in the engine's own words. The generator
    asked a name whether the food was heavy."""
    assert schema.to_kb_row(_ok(guna=("guru",)))["ayurvedic"]["agni_effect"] == "heavy"
    assert schema.to_kb_row(_ok(guna=("laghu",)))["ayurvedic"]["agni_effect"] == "easy"
    assert schema.to_kb_row(_ok(guna=("tikshna",)))["ayurvedic"]["agni_effect"] == "moderate"


def test_preparation_states_are_two_rows_not_one():
    """Ardraka and Shunthi have opposite indications. `diet_foods.json` has one row
    per ingredient and no way to say which state it describes, which is why
    `ayurvedic_foods.json` contradicts it and both are seeded into one corpus."""
    fresh = _ok(prep_state="fresh")
    dry = _ok(prep_state="dry")
    assert fresh["id"] != dry["id"]


# ── The first tranche ─────────────────────────────────────────────────────────

def test_the_spice_tranche_validates_and_keeps_the_existing_ids():
    """Ids match the keys already in `diet_foods.json` so the migration maps
    one-to-one and coverage can be counted."""
    import json
    kb = json.loads((Path(__file__).resolve().parent.parent / "data" /
                     "knowledge_base" / "diet_foods.json").read_text(encoding="utf-8"))
    existing = {f["id"] for f in kb}
    assert {f["id"] for f in SPICES} <= existing


def test_the_two_classical_exceptions_the_old_schema_flattened():
    """Every row in the `spice` category currently gets `rasa: ["pungent"], virya:
    heating, vipaka: pungent`. Two of these ten contradict that in the texts."""
    by_id = {f["id"]: f for f in SPICES}
    assert by_id["ginger_dry_saunth"]["vipaka"] == "madhura"   # not katu
    assert by_id["cardamom_elaichi"]["virya"] == "shita"       # not ushna


# ── The completeness gate ─────────────────────────────────────────────────────

def test_the_builder_refuses_to_write_a_partial_library(capsys, monkeypatch):
    """A half-migrated file is worse than either end of the migration: it would drop
    the unauthored foods from the fallback engine and from the RAG nutrition
    collection, and a corpus returning less is not an error, so nothing would go red.

    The library is complete now, so the gate is exercised against a truncated tranche
    list — the state it was actually written to protect, which no longer occurs
    naturally and would otherwise stop being tested at the moment it stopped firing.
    """
    monkeypatch.setattr(builder, "TRANCHES", builder.TRANCHES[:1])
    monkeypatch.setattr(sys, "argv", ["build_diet_library.py", "--write"])
    assert builder.main() == 1
    assert "REFUSING to write" in capsys.readouterr().err


def test_the_library_covers_every_food_the_knowledge_base_holds():
    done, todo, extra = builder.coverage()
    assert not todo, f"still derived: {sorted(todo)}"
    assert not extra, f"authored but matching no knowledge-base id: {sorted(extra)}"
    assert len(done) == 150


def test_the_written_file_matches_the_library(monkeypatch):
    """`--check` is what stops the knowledge base and the spec drifting apart, the way
    `gym_exercises.json` and its spec are held together."""
    monkeypatch.setattr(sys, "argv", ["build_diet_library.py", "--check"])
    assert builder.main() == 0


def test_check_fails_on_a_library_that_lost_rows(capsys, monkeypatch):
    """The other half of `--check`, and the one that matters in CI.

    While the library was being authored, an incomplete library was the expected
    state and `--check` printed a note and passed. Now that every food has an
    authored row, incompleteness means rows went missing — so it must be red.
    `test_the_written_file_matches_the_library` runs the same code path, and while
    that early return stood it would have passed green on a library missing 140
    foods: the same invisible failure as a RAG corpus that returns less.
    """
    monkeypatch.setattr(builder, "TRANCHES", builder.TRANCHES[:1])
    monkeypatch.setattr(sys, "argv", ["build_diet_library.py", "--check"])
    assert builder.main() == 1
    assert "library is incomplete" in capsys.readouterr().err


def test_no_food_still_carries_the_generators_signature():
    """The four measurements that identified the derived library. They are assertions
    now rather than observations, so a future edit cannot quietly reintroduce them."""
    rows = builder.library()
    assert len({tuple(r["ayurvedic"]["rasa"]) for r in rows}) > 15, "rasa has collapsed"
    assert len({tuple(r["season_suitable"]) for r in rows}) > 10, "ritu has collapsed"
    assert all(r["ayurvedic"]["guna"] for r in rows), "a row lost its guna"
    assert not [r for r in rows if r["ayurvedic"]["best_for"] == []
                and r["apathya_for"] == []], "a row indicates and contraindicates nothing"


def test_the_generator_is_retired():
    src = (Path(__file__).resolve().parent.parent / "scripts"
           / "seed_diet_foods.py").read_text(encoding="utf-8")
    assert "RETIRED" in src and "sys.exit(1)" in src


# ── The library as it grows ───────────────────────────────────────────────────

def test_every_authored_row_validates_and_ids_are_unique():
    """`library()` re-validates rather than trusting `spec.F`, because a tranche is a
    list of plain dicts and an edit after construction would otherwise slip past."""
    rows = builder.library()
    ids = [r["id"] for r in rows]
    assert len(ids) == len(set(ids)), "duplicate id across tranches"


def test_every_authored_id_exists_in_the_knowledge_base():
    """Ids match the keys already in `diet_foods.json` so the migration maps
    one-to-one and `coverage()` counts something real. A typo makes a row that is
    authored, valid, and connected to nothing."""
    import json
    kb = json.loads((Path(__file__).resolve().parent.parent / "data" /
                     "knowledge_base" / "diet_foods.json").read_text(encoding="utf-8"))
    existing = {f["id"] for f in kb}
    orphans = sorted({r["id"] for r in builder.library()} - existing)
    assert not orphans, f"authored rows matching no knowledge-base id: {orphans}"


def test_sour_vipaka_now_occurs():
    """Amla Vipaka is one of the three classical values and appears on none of the
    150 derived rows, because `seed_diet_foods.py` can only write madhura or katu.
    Every sour food in the current library is therefore mislabelled."""
    rows = builder.library()
    sour = [r["id"] for r in rows if r["ayurvedic"]["vipaka"] == "sour"]
    assert sour, "the value the derived library cannot reach is still unreached"


def test_the_library_is_more_various_than_the_thing_it_replaces():
    """The derived library has six distinct rasa combinations across 150 foods and one
    distinct `season_suitable` value. Those numbers are the signature of a category
    table, and they are what this library exists to beat — not a target, a floor."""
    rows = builder.library()
    rasa_combos = {tuple(r["ayurvedic"]["rasa"]) for r in rows}
    ritu_sets = {tuple(r["season_suitable"]) for r in rows}
    assert len(rasa_combos) > 6, f"only {len(rasa_combos)} rasa combinations authored"
    assert len(ritu_sets) > 1, "every authored food suits every season — check the ritu field"


def test_no_authored_row_carries_a_placeholder_macro_block():
    """109 of 150 derived rows share a per-category constant — 27 vegetables report
    identical calories. Provenance is what makes that visible, so it is required."""
    for row in builder.library():
        assert row["nutrition_source"] in schema.NUTRITION_SOURCES


def test_modern_foods_say_so_and_show_their_reasoning():
    """A fifth of this knowledge base is twentieth-century food with no entry in any
    nighantu. The generator gave those rows a rasa and a virya with exactly the
    confidence it gave Shunthi one, and nothing recorded the difference."""
    rows = builder.library()
    extrapolated = [r for r in rows if r["nighantu_ref"]["text"] == "modern_extrapolated"]
    assert extrapolated, "no row admits to being an extrapolation — check the vocabulary"
    for row in extrapolated:
        varga = row["nighantu_ref"]["varga"]
        assert len(varga) >= 25, f"{row['id']} extrapolates without showing its reasoning"
        assert "xtrapolated" in varga, f"{row['id']} does not say it is extrapolated"


def test_curd_and_buttermilk_are_not_the_same_row():
    """Made from the same milk and opposite prescriptions: Dadhi is guru, abhishyandi
    and the first Apathya named for Amavata; Takra is laghu, deepana and the classical
    Grahani medicine. Under one `dairy` category profile they differed only by name."""
    by_id = {r["id"]: r for r in builder.library()}
    dadhi, takra = by_id["curd_yogurt"], by_id["buttermilk_chaas"]
    assert dadhi["ayurvedic"]["dosha_effect"]["kapha"] > 0
    assert takra["ayurvedic"]["dosha_effect"]["kapha"] < 0
    assert "amavata" in dadhi["apathya_for"]
    assert "grahani" in takra["pathya_for"]
